default: &default
  adapter: mysql2
  encoding: utf8
  pool: 5
  username: root
  password:
  socket: /tmp/mysql.sock

development:
  <<: *default
  database: best_eleven

test:
  <<: *default
  database: best_eleven

production:
  <<: *default
  database: best_eleven
#  password: <%= ENV['TEST-MYSQL_DATABASE_PASSWORD'] %>
