defaults: &defaults

development:
  <<: *defaults
  twitter:
    consumer_key: cIXurcheLQEE5HjgO1VJn7CXZ
    consumer_secret: sXLXy374wMc9kJAAiexWe68hIqRtjqytHHWG4UXQv8ol7xwuxO
  tweet_setting:
    text: "time %s"

test:
  <<: *defaults

production:
  <<: *defaults
  twitter:
    consumer_key: cIXurcheLQEE5HjgO1VJn7CXZ
    consumer_secret: sXLXy374wMc9kJAAiexWe68hIqRtjqytHHWG4UXQv8ol7xwuxO
  tweet_setting:
    text: "time %s"
