defaults: &defaults

development:
  <<: *defaults
  twitter:
    consumer_key: <%= ENV["TW_CONSUMER_KEY"] %>
    consumer_secret: <%= ENV["TW_CONSUMER_SECRET"] %>
  s3:
    access_key_id: <%= ENV["S3_ACCESS_KEY_ID"] %>
    secret_access_key: <%= ENV["S3_SECRET_ACCESS_KEY"] %>
    region: ap-northeast-1
    buckets_name: best-eleven-contents
    image_url_path: http://s3-ap-northeast-1.amazonaws.com/best-eleven-contents/

test:
  <<: *defaults

production:
  <<: *defaults
  twitter:
    consumer_key: <%= ENV["TW_CONSUMER_KEY"] %>
    consumer_secret: <%= ENV["TW_CONSUMER_SECRET"] %>
  s3:
    access_key_id: <%= ENV["S3_ACCESS_KEY_ID"] %>
    secret_access_key: <%= ENV["S3_SECRET_ACCESS_KEY"] %>
    region: <%= ENV["AWS_REGION"] %>
    buckets_name: <%= ENV["BUCKETS_NAME"] %>
    image_url_path: <%= ENV["S3_IMAGE_URL_PATH"] %>

