# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).

[
  { :id => 1, :type_id => 1, :full_name => 'ナス', :short_name => 'ナス', :valid_st => 1 },
  { :id => 2, :type_id => 1, :full_name => '豆腐', :short_name => '豆腐', :valid_st => 1 },
  { :id => 3, :type_id => 1, :full_name => 'しじみ', :short_name => 'しじみ', :valid_st => 1 },
  { :id => 4, :type_id => 1, :full_name => 'ほうれん草', :short_name => 'ほうれん草', :valid_st => 1 },
  { :id => 5, :type_id => 1, :full_name => '大根', :short_name => '大根', :valid_st => 1 },
  { :id => 6, :type_id => 1, :full_name => '豚汁', :short_name => '豚汁', :valid_st => 1 },
  { :id => 7, :type_id => 1, :full_name => 'ふ', :short_name => 'ふ', :valid_st => 1 },
  { :id => 8, :type_id => 1, :full_name => 'キャベツ', :short_name => 'キャベツ', :valid_st => 1 },
  { :id => 9, :type_id => 1, :full_name => 'カボチャ', :short_name => 'カボチャ', :valid_st => 1 },
  { :id => 10, :type_id => 1, :full_name => '玉ねぎ', :short_name => '玉ねぎ', :valid_st => 1 },
  { :id => 11, :type_id => 1, :full_name => '油揚げ', :short_name => '油揚げ', :valid_st => 1 },
  { :id => 12, :type_id => 1, :full_name => '長ネギ', :short_name => '長ネギ', :valid_st => 1 },
  { :id => 13, :type_id => 1, :full_name => 'しめじ', :short_name => 'しめじ', :valid_st => 1 },
  { :id => 14, :type_id => 1, :full_name => 'えのき', :short_name => 'えのき', :valid_st => 1 },
  { :id => 15, :type_id => 1, :full_name => '白菜', :short_name => '白菜', :valid_st => 1 },
  { :id => 16, :type_id => 1, :full_name => 'カブ', :short_name => 'カブ', :valid_st => 1 },
  { :id => 17, :type_id => 1, :full_name => 'アオサ', :short_name => 'アオサ', :valid_st => 1 },
  { :id => 18, :type_id => 2, :full_name => '医師', :short_name => '医師', :valid_st => 1 },
  { :id => 19, :type_id => 2, :full_name => '板前', :short_name => '板前', :valid_st => 1 },
  { :id => 20, :type_id => 2, :full_name => 'プログラマー', :short_name => 'プログラマー', :valid_st => 1 },
  { :id => 21, :type_id => 2, :full_name => 'お笑い芸人', :short_name => 'お笑い芸人', :valid_st => 1 },
  { :id => 22, :type_id => 2, :full_name => '音楽家', :short_name => '音楽家', :valid_st => 1 },
  { :id => 23, :type_id => 2, :full_name => '看護師', :short_name => '看護師', :valid_st => 1 },
  { :id => 24, :type_id => 2, :full_name => '起業家', :short_name => '起業家', :valid_st => 1 },
  { :id => 25, :type_id => 2, :full_name => '気象予報士', :short_name => '気象予報士', :valid_st => 1 },
  { :id => 26, :type_id => 2, :full_name => 'キックボクサー', :short_name => 'キックボクサー', :valid_st => 1 },
  { :id => 27, :type_id => 2, :full_name => '警備員', :short_name => '警備員', :valid_st => 1 },
  { :id => 28, :type_id => 2, :full_name => 'ダンサー', :short_name => 'ダンサー', :valid_st => 1 },
  { :id => 29, :type_id => 2, :full_name => '配管工', :short_name => '配管工', :valid_st => 1 },
  { :id => 30, :type_id => 2, :full_name => '農家', :short_name => '農家', :valid_st => 1 },
  { :id => 31, :type_id => 2, :full_name => '登山家', :short_name => '登山家', :valid_st => 1 },
  { :id => 32, :type_id => 2, :full_name => 'テニス選手', :short_name => 'テニス選手', :valid_st => 1 },
  { :id => 33, :type_id => 2, :full_name => '力士', :short_name => '力士', :valid_st => 1 },
  { :id => 34, :type_id => 2, :full_name => 'ラグビー選手', :short_name => 'ラグビー選手', :valid_st => 1 },
  { :id => 35, :type_id => 2, :full_name => 'レスキュー隊員', :short_name => 'レスキュー隊員', :valid_st => 1 },
  { :id => 36, :type_id => 2, :full_name => 'レーサー', :short_name => 'レーサー', :valid_st => 1 },
  { :id => 37, :type_id => 2, :full_name => 'バスケットボール選手', :short_name => 'バスケットボール選手', :valid_st => 1 },
  { :id => 38, :type_id => 2, :full_name => '占い師', :short_name => '占い師', :valid_st => 1 },
  { :id => 39, :type_id => 2, :full_name => '宇宙飛行士', :short_name => '宇宙飛行士', :valid_st => 1 },
  { :id => 40, :type_id => 2, :full_name => '警察官', :short_name => '警察官', :valid_st => 1 },
  { :id => 41, :type_id => 2, :full_name => 'プロ野球選手', :short_name => 'プロ野球選手', :valid_st => 1 },
  { :id => 42, :type_id => 2, :full_name => '柔道家', :short_name => '柔道家', :valid_st => 1 },
  { :id => 43, :type_id => 2, :full_name => 'プロボクサー', :short_name => 'プロボクサー', :valid_st => 1 },
  { :id => 44, :type_id => 2, :full_name => 'プロゴルファー', :short_name => 'プロゴルファー', :valid_st => 1 },
  { :id => 45, :type_id => 2, :full_name => '卓球選手', :short_name => '卓球選手', :valid_st => 1 },
  { :id => 46, :type_id => 2, :full_name => 'プロレスラー', :short_name => 'プロレスラー', :valid_st => 1 },
  { :id => 47, :type_id => 2, :full_name => '空手家', :short_name => '空手家', :valid_st => 1 },
  { :id => 48, :type_id => 1, :full_name => 'なめこ', :short_name => 'なめこ', :valid_st => 1 },
  { :id => 49, :type_id => 1, :full_name => 'わかめ', :short_name => 'わかめ', :valid_st => 1 },
  { :id => 50, :type_id => 3, :full_name => '川口能活', :short_name => '川口能活', :valid_st => 1 },
  { :id => 51, :type_id => 3, :full_name => '川島永嗣', :short_name => '川島永嗣', :valid_st => 1 },
  { :id => 52, :type_id => 3, :full_name => '楢崎正剛', :short_name => '楢崎正剛', :valid_st => 1 },
  { :id => 53, :type_id => 3, :full_name => '秋田豊', :short_name => '秋田豊', :valid_st => 1 },
  { :id => 54, :type_id => 3, :full_name => '伊野波雅彦', :short_name => '伊野波雅彦', :valid_st => 1 },
  { :id => 55, :type_id => 3, :full_name => '井原正巳', :short_name => '井原正巳', :valid_st => 1 },
  { :id => 56, :type_id => 3, :full_name => '内田篤人', :short_name => '内田篤人', :valid_st => 1 },
  { :id => 57, :type_id => 3, :full_name => '小村徳男', :short_name => '小村徳男', :valid_st => 1 },
  { :id => 58, :type_id => 3, :full_name => '加地亮', :short_name => '加地亮', :valid_st => 1 },
  { :id => 59, :type_id => 3, :full_name => '駒野友一', :short_name => '駒野友一', :valid_st => 1 },
  { :id => 60, :type_id => 3, :full_name => '今野泰幸', :short_name => '今野泰幸', :valid_st => 1 },
  { :id => 61, :type_id => 3, :full_name => '三都主アレサンドロ', :short_name => '三都主', :valid_st => 1 },
  { :id => 62, :type_id => 3, :full_name => '相馬直樹', :short_name => '相馬直樹', :valid_st => 1 },
  { :id => 63, :type_id => 3, :full_name => '田中マルクス闘莉王', :short_name => '闘莉王', :valid_st => 1 },
  { :id => 64, :type_id => 3, :full_name => '坪井慶介', :short_name => '坪井慶介', :valid_st => 1 },
  { :id => 65, :type_id => 3, :full_name => '中澤佑二', :short_name => '中澤佑二', :valid_st => 1 },
  { :id => 66, :type_id => 3, :full_name => '中田浩二', :short_name => '中田浩二', :valid_st => 1 },
  { :id => 67, :type_id => 3, :full_name => '長友佑都', :short_name => '長友佑都', :valid_st => 1 },
  { :id => 68, :type_id => 3, :full_name => '名良橋晃', :short_name => '名良橋晃', :valid_st => 1 },
  { :id => 69, :type_id => 3, :full_name => '松田直樹', :short_name => '松田直樹', :valid_st => 1 },
  { :id => 70, :type_id => 3, :full_name => '宮本恒靖', :short_name => '宮本恒靖', :valid_st => 1 },
  { :id => 71, :type_id => 3, :full_name => '森岡隆三', :short_name => '森岡隆三', :valid_st => 1 },
  { :id => 72, :type_id => 3, :full_name => '吉田麻也', :short_name => '吉田麻也', :valid_st => 1 },
  { :id => 73, :type_id => 3, :full_name => '阿部勇樹', :short_name => '阿部勇樹', :valid_st => 1 },
  { :id => 74, :type_id => 3, :full_name => '伊東輝悦', :short_name => '伊東輝悦', :valid_st => 1 },
  { :id => 75, :type_id => 3, :full_name => '稲本潤一', :short_name => '稲本潤一', :valid_st => 1 },
  { :id => 76, :type_id => 3, :full_name => '遠藤保仁', :short_name => '遠藤保仁', :valid_st => 1 },
  { :id => 77, :type_id => 3, :full_name => '小笠原満男', :short_name => '小笠原満男', :valid_st => 1 },
  { :id => 78, :type_id => 3, :full_name => '小野伸二', :short_name => '小野伸二', :valid_st => 1 },
  { :id => 79, :type_id => 3, :full_name => '香川真司', :short_name => '香川真司', :valid_st => 1 },
  { :id => 80, :type_id => 3, :full_name => '清武弘嗣', :short_name => '清武弘嗣', :valid_st => 1 },
  { :id => 81, :type_id => 3, :full_name => '戸田和幸', :short_name => '戸田和幸', :valid_st => 1 },
  { :id => 82, :type_id => 3, :full_name => '中田英寿', :short_name => '中田英寿', :valid_st => 1 },
  { :id => 83, :type_id => 3, :full_name => '中村憲剛', :short_name => '中村憲剛', :valid_st => 1 },
  { :id => 84, :type_id => 3, :full_name => '中村俊輔', :short_name => '中村俊輔', :valid_st => 1 },
  { :id => 85, :type_id => 3, :full_name => '名波浩', :short_name => '名波浩', :valid_st => 1 },
  { :id => 86, :type_id => 3, :full_name => '長谷部誠', :short_name => '長谷部誠', :valid_st => 1 },
  { :id => 87, :type_id => 3, :full_name => '服部年宏', :short_name => '服部年宏', :valid_st => 1 },
  { :id => 88, :type_id => 3, :full_name => '福西崇史', :short_name => '福西崇史', :valid_st => 1 },
  { :id => 89, :type_id => 3, :full_name => '本田圭佑', :short_name => '本田圭佑', :valid_st => 1 },
  { :id => 90, :type_id => 3, :full_name => '松井大輔', :short_name => '松井大輔', :valid_st => 1 },
  { :id => 91, :type_id => 3, :full_name => '明神智和', :short_name => '明神智和', :valid_st => 1 },
  { :id => 92, :type_id => 3, :full_name => '山口素弘', :short_name => '山口素弘', :valid_st => 1 },

  { :id => 93, :type_id => 3, :full_name => '大久保嘉人', :short_name => '大久保嘉人', :valid_st => 1 },
  { :id => 94, :type_id => 3, :full_name => '大黒将志', :short_name => '大黒将志', :valid_st => 1 },
  { :id => 95, :type_id => 3, :full_name => '岡崎慎司', :short_name => '岡崎慎司', :valid_st => 1 },
  { :id => 96, :type_id => 3, :full_name => '岡野雅行', :short_name => '岡野雅行', :valid_st => 1 },
  { :id => 97, :type_id => 3, :full_name => '城彰二', :short_name => '城彰二', :valid_st => 1 },
  { :id => 98, :type_id => 3, :full_name => '鈴木隆行', :short_name => '鈴木隆行', :valid_st => 1 },
  { :id => 99, :type_id => 3, :full_name => '高原直泰', :short_name => '高原直泰', :valid_st => 1 },
  { :id => 100, :type_id => 3, :full_name => '玉田圭司', :short_name => '玉田圭司', :valid_st => 1 },
  { :id => 101, :type_id => 3, :full_name => '中山雅史', :short_name => '中山雅史', :valid_st => 1 },
  { :id => 102, :type_id => 3, :full_name => '西澤明訓', :short_name => '西澤明訓', :valid_st => 1 },
  { :id => 103, :type_id => 3, :full_name => '巻誠一郎', :short_name => '巻誠一郎', :valid_st => 1 },
  { :id => 104, :type_id => 3, :full_name => '森島寛晃', :short_name => '森島寛晃', :valid_st => 1 },
  { :id => 105, :type_id => 3, :full_name => '柳沢敦', :short_name => '柳沢敦', :valid_st => 1 },
  { :id => 106, :type_id => 3, :full_name => '呂比須ワグナー', :short_name => '呂比須', :valid_st => 1 },
  { :id => 107, :type_id => 1, :full_name => 'もやし', :short_name => 'もやし', :valid_st => 1 },
  { :id => 108, :type_id => 1, :full_name => 'ひじき', :short_name => 'ひじき', :valid_st => 1 },
  { :id => 109, :type_id => 1, :full_name => 'たけのこ', :short_name => 'たけのこ', :valid_st => 1 },
  { :id => 110, :type_id => 1, :full_name => 'みょうが', :short_name => 'みょうが', :valid_st => 1 },
  { :id => 111, :type_id => 1, :full_name => 'れんこん', :short_name => 'れんこん', :valid_st => 1 },
  { :id => 112, :type_id => 1, :full_name => 'とろろ昆布', :short_name => 'とろろ昆布', :valid_st => 1 },
  { :id => 113, :type_id => 1, :full_name => 'ちくわ', :short_name => 'ちくわ', :valid_st => 1 },
  { :id => 114, :type_id => 1, :full_name => 'あら汁', :short_name => 'あら汁', :valid_st => 1 },
  { :id => 115, :type_id => 1, :full_name => 'じゃがいも', :short_name => 'じゃがいも', :valid_st => 1 },
  { :id => 116, :type_id => 4, :full_name => 'イルクナー', :short_name => 'イルクナー', :valid_st => 1 },
  { :id => 117, :type_id => 4, :full_name => 'カシージャス', :short_name => 'カシージャス', :valid_st => 1 },
  { :id => 118, :type_id => 4, :full_name => 'ディエゴ・ロペス', :short_name => 'D・ロペス', :valid_st => 1 },
  { :id => 119, :type_id => 4, :full_name => 'ナバス', :short_name => 'ナバス', :valid_st => 1 },
  { :id => 120, :type_id => 4, :full_name => 'アルビオル', :short_name => 'アルビオル', :valid_st => 1 },
  { :id => 121, :type_id => 4, :full_name => 'アルベロア', :short_name => 'アルベロア', :valid_st => 1 },
  { :id => 122, :type_id => 4, :full_name => 'イバン・カンポ', :short_name => 'I・カンポ', :valid_st => 1 },
  { :id => 123, :type_id => 4, :full_name => 'イエロ', :short_name => 'イエロ', :valid_st => 1 },
  { :id => 124, :type_id => 4, :full_name => 'ヴァラン', :short_name => 'ヴァラン', :valid_st => 1 },
  { :id => 125, :type_id => 4, :full_name => 'エインセ', :short_name => 'エインセ', :valid_st => 1 },
  { :id => 126, :type_id => 4, :full_name => 'エルゲラ', :short_name => 'エルゲラ', :valid_st => 1 },
  { :id => 127, :type_id => 4, :full_name => 'カルバハル', :short_name => 'カルバハル', :valid_st => 1 },
  { :id => 128, :type_id => 4, :full_name => 'カンナバーロ', :short_name => 'カンナバーロ', :valid_st => 1 },
  { :id => 129, :type_id => 4, :full_name => 'コエントラン', :short_name => 'コエントラン', :valid_st => 1 },
  { :id => 130, :type_id => 4, :full_name => 'サルガド', :short_name => 'サルガド', :valid_st => 1 },
  { :id => 131, :type_id => 4, :full_name => 'セルヒオ・ラモス', :short_name => 'S・ラモス', :valid_st => 1 },
  { :id => 132, :type_id => 4, :full_name => 'パボン', :short_name => 'パボン', :valid_st => 1 },
  { :id => 133, :type_id => 4, :full_name => 'ペペ', :short_name => 'ペペ', :valid_st => 1 },
  { :id => 134, :type_id => 4, :full_name => 'マルセロ', :short_name => 'マルセロ', :valid_st => 1 },
  { :id => 135, :type_id => 4, :full_name => 'ラウール・ブラボ', :short_name => 'R・ブラボ', :valid_st => 1 },
  { :id => 136, :type_id => 4, :full_name => 'リカルド・カルヴァーリョ', :short_name => 'R・カルヴァーリョ', :valid_st => 1 },
  { :id => 137, :type_id => 4, :full_name => 'ロベルト・カルロス', :short_name => 'R・カルロス', :valid_st => 1 },
  { :id => 138, :type_id => 4, :full_name => 'イスコ', :short_name => 'イスコ', :valid_st => 1 },
  { :id => 139, :type_id => 4, :full_name => 'エジル', :short_name => 'エジル', :valid_st => 1 },
  { :id => 140, :type_id => 4, :full_name => 'カカ', :short_name => 'カカ', :valid_st => 1 },
  { :id => 141, :type_id => 4, :full_name => 'ガゴ', :short_name => 'ガゴ', :valid_st => 1 },
  { :id => 142, :type_id => 4, :full_name => 'カンビアッソ', :short_name => 'カンビアッソ', :valid_st => 1 },
  { :id => 143, :type_id => 4, :full_name => 'グティ', :short_name => 'グティ', :valid_st => 1 },
  { :id => 144, :type_id => 4, :full_name => 'グラネロ', :short_name => 'グラネロ', :valid_st => 1 },
  { :id => 145, :type_id => 4, :full_name => 'クロース', :short_name => 'クロース', :valid_st => 1 },
  { :id => 146, :type_id => 4, :full_name => 'ケディラ', :short_name => 'ケディラ', :valid_st => 1 },
  { :id => 147, :type_id => 4, :full_name => 'ジダン', :short_name => 'ジダン', :valid_st => 1 },
  { :id => 148, :type_id => 4, :full_name => 'シャビ・アロンソ', :short_name => 'X・アロンソ', :valid_st => 1 },
  { :id => 149, :type_id => 4, :full_name => 'スナイデル', :short_name => 'スナイデル', :valid_st => 1 },
  { :id => 150, :type_id => 4, :full_name => 'セードルフ', :short_name => 'セードルフ', :valid_st => 1 },
  { :id => 151, :type_id => 4, :full_name => 'ソラーリ', :short_name => 'ソラーリ', :valid_st => 1 },
  { :id => 152, :type_id => 4, :full_name => 'ディ・マリア', :short_name => 'ディ・マリア', :valid_st => 1 },
  { :id => 153, :type_id => 4, :full_name => 'ハメス・ロドリゲス', :short_name => 'J・ロドリゲス', :valid_st => 1 },
  { :id => 154, :type_id => 4, :full_name => 'ファン・デル・ファールト', :short_name => 'V・D・ファールト', :valid_st => 1 },
  { :id => 155, :type_id => 4, :full_name => 'フィーゴ', :short_name => 'フィーゴ', :valid_st => 1 },
  { :id => 156, :type_id => 4, :full_name => 'ベッカム', :short_name => 'ベッカム', :valid_st => 1 },
  { :id => 157, :type_id => 4, :full_name => 'マアマドゥ・ディアラ', :short_name => 'M・ディアラ', :valid_st => 1 },
  { :id => 158, :type_id => 4, :full_name => 'マケレレ', :short_name => 'マケレレ', :valid_st => 1 },
  { :id => 159, :type_id => 4, :full_name => 'モドリッチ', :short_name => 'モドリッチ', :valid_st => 1 },
  { :id => 160, :type_id => 4, :full_name => 'ラウドルップ', :short_name => 'ラウドルップ', :valid_st => 1 },
  { :id => 161, :type_id => 4, :full_name => 'ラサナ・ディアラ', :short_name => 'L・ディアラ', :valid_st => 1 },
  { :id => 162, :type_id => 4, :full_name => 'ルイス・エンリケ', :short_name => 'L・エンリケ', :valid_st => 1 },
  { :id => 163, :type_id => 4, :full_name => 'レドンド', :short_name => 'レドンド', :valid_st => 1 },
  { :id => 164, :type_id => 4, :full_name => 'イグアイン', :short_name => 'イグアイン', :valid_st => 1 },
  { :id => 165, :type_id => 4, :full_name => 'エルナンデス', :short_name => 'エルナンデス', :valid_st => 1 },
  { :id => 166, :type_id => 4, :full_name => 'オーウェン', :short_name => 'オーウェン', :valid_st => 1 },
  { :id => 167, :type_id => 4, :full_name => 'クリスティアーノ・ロナウド', :short_name => 'C・ロナウド', :valid_st => 1 },
  { :id => 168, :type_id => 4, :full_name => 'シューケル', :short_name => 'シューケル', :valid_st => 1 },
  { :id => 169, :type_id => 4, :full_name => 'ファン・ニステルローイ', :short_name => 'V・ニステルローイ', :valid_st => 1 },
  { :id => 170, :type_id => 4, :full_name => 'ベイル', :short_name => 'ベイル', :valid_st => 1 },
  { :id => 171, :type_id => 4, :full_name => 'ベンゼマ', :short_name => 'ベンゼマ', :valid_st => 1 },
  { :id => 172, :type_id => 4, :full_name => 'ミヤトヴィッチ', :short_name => 'ミヤトヴィッチ', :valid_st => 1 },
  { :id => 173, :type_id => 4, :full_name => 'モリエンテス', :short_name => 'モリエンテス', :valid_st => 1 },
  { :id => 174, :type_id => 4, :full_name => 'ラウール', :short_name => 'ラウール', :valid_st => 1 },
  { :id => 175, :type_id => 4, :full_name => 'ロッベン', :short_name => 'ロッベン', :valid_st => 1 },
  { :id => 176, :type_id => 4, :full_name => 'ロナウド', :short_name => 'ロナウド', :valid_st => 1 },
  { :id => 177, :type_id => 4, :full_name => 'ロビーニョ', :short_name => 'ロビーニョ', :valid_st => 1 },
  { :id => 178, :type_id => 5, :full_name => '朝青龍', :short_name => '朝青龍', :valid_st => 1 },
  { :id => 179, :type_id => 5, :full_name => '朝原宣治', :short_name => '朝原宣治', :valid_st => 1 },
  { :id => 180, :type_id => 5, :full_name => 'アントニオ猪木', :short_name => 'A猪木', :valid_st => 1 },
  { :id => 181, :type_id => 5, :full_name => '五十嵐圭', :short_name => '五十嵐圭', :valid_st => 1 },
  { :id => 182, :type_id => 5, :full_name => '池谷直樹', :short_name => '池谷直樹', :valid_st => 1 },
  { :id => 183, :type_id => 5, :full_name => '石川遼', :short_name => '石川遼', :valid_st => 1 },
  { :id => 184, :type_id => 5, :full_name => 'イチロー', :short_name => 'イチロー', :valid_st => 1 },
  { :id => 185, :type_id => 5, :full_name => '内村航平', :short_name => '内村航平', :valid_st => 1 },
  { :id => 186, :type_id => 5, :full_name => '太田雄貴', :short_name => '太田雄貴', :valid_st => 1 },
  { :id => 187, :type_id => 5, :full_name => '大谷翔平', :short_name => '大谷翔平', :valid_st => 1 },
  { :id => 188, :type_id => 5, :full_name => '大畑大介', :short_name => '大畑大介', :valid_st => 1 },
  { :id => 189, :type_id => 5, :full_name => '大山倍達', :short_name => '大山倍達', :valid_st => 1 },
  { :id => 190, :type_id => 5, :full_name => '葛西紀明', :short_name => '葛西紀明', :valid_st => 1 },
  { :id => 191, :type_id => 5, :full_name => '嘉納治五郎', :short_name => '嘉納治五郎', :valid_st => 1 },
  { :id => 192, :type_id => 5, :full_name => '亀田興毅', :short_name => '亀田興毅', :valid_st => 1 },
  { :id => 193, :type_id => 5, :full_name => '亀田大毅', :short_name => '亀田大毅', :valid_st => 1 },
  { :id => 194, :type_id => 5, :full_name => '亀田和毅', :short_name => '亀田和毅', :valid_st => 1 },
  { :id => 195, :type_id => 5, :full_name => '川合俊一', :short_name => '川合俊一', :valid_st => 1 },
  { :id => 196, :type_id => 5, :full_name => '木下典明', :short_name => '木下典明', :valid_st => 1 },
  { :id => 197, :type_id => 5, :full_name => '桐生祥秀', :short_name => '桐生祥秀', :valid_st => 1 },
  { :id => 198, :type_id => 5, :full_name => '清水宏保', :short_name => '清水宏保', :valid_st => 1 },
  { :id => 199, :type_id => 5, :full_name => 'ジャイアント馬場', :short_name => 'G馬場', :valid_st => 1 },
  { :id => 200, :type_id => 5, :full_name => '照英', :short_name => '照英', :valid_st => 1 },
  { :id => 201, :type_id => 5, :full_name => '白井健三', :short_name => '白井健三', :valid_st => 1 },
  { :id => 202, :type_id => 5, :full_name => '瀬戸大也', :short_name => '瀬戸大也', :valid_st => 1 },
  { :id => 203, :type_id => 5, :full_name => '宗茂', :short_name => '宗茂', :valid_st => 1 },
  { :id => 204, :type_id => 5, :full_name => '宗猛', :short_name => '宗猛', :valid_st => 1 },
  { :id => 205, :type_id => 5, :full_name => '高橋大輔', :short_name => '高橋大輔', :valid_st => 1 },
  { :id => 206, :type_id => 5, :full_name => '武豊', :short_name => '武豊', :valid_st => 1 },
  { :id => 207, :type_id => 5, :full_name => '武井壮', :short_name => '武井壮', :valid_st => 1 },
  { :id => 208, :type_id => 5, :full_name => '田中将大', :short_name => '田中将大', :valid_st => 1 },
  { :id => 209, :type_id => 5, :full_name => '谷口浩美', :short_name => '谷口浩美', :valid_st => 1 },
  { :id => 210, :type_id => 5, :full_name => '田臥勇太', :short_name => '田臥勇太', :valid_st => 1 },
  { :id => 211, :type_id => 5, :full_name => 'ダルビッシュ有', :short_name => 'ダルビッシュ', :valid_st => 1 },
  { :id => 212, :type_id => 5, :full_name => '中田大輔', :short_name => '中田大輔', :valid_st => 1 },
  { :id => 213, :type_id => 5, :full_name => '中野浩一', :short_name => '中野浩一', :valid_st => 1 },
  { :id => 214, :type_id => 5, :full_name => '錦織圭', :short_name => '錦織圭', :valid_st => 1 },
  { :id => 215, :type_id => 5, :full_name => '野村忠宏', :short_name => '野村忠宏', :valid_st => 1 },
  { :id => 216, :type_id => 5, :full_name => '萩野公介', :short_name => '萩野公介', :valid_st => 1 },
  { :id => 217, :type_id => 5, :full_name => '白鵬', :short_name => '白鵬', :valid_st => 1 },
  { :id => 218, :type_id => 5, :full_name => '羽生結弦', :short_name => '羽生結弦', :valid_st => 1 },
  { :id => 219, :type_id => 5, :full_name => '魔裟斗', :short_name => '魔裟斗', :valid_st => 1 },
  { :id => 220, :type_id => 5, :full_name => '松岡修造', :short_name => '松岡修造', :valid_st => 1 },
  { :id => 221, :type_id => 5, :full_name => '松山英樹', :short_name => '松山英樹', :valid_st => 1 },
  { :id => 222, :type_id => 5, :full_name => '水谷隼', :short_name => '水谷隼', :valid_st => 1 },
  { :id => 223, :type_id => 5, :full_name => '宮崎大輔', :short_name => '宮崎大輔', :valid_st => 1 },
  { :id => 224, :type_id => 5, :full_name => '村上幸史', :short_name => '村上幸史', :valid_st => 1 },
  { :id => 225, :type_id => 5, :full_name => '室伏広治', :short_name => '室伏広治', :valid_st => 1 },
  { :id => 226, :type_id => 5, :full_name => '山下泰裕', :short_name => '山下泰裕', :valid_st => 1 },
  { :id => 227, :type_id => 5, :full_name => '山田勝己', :short_name => '山田勝己', :valid_st => 1 },
  { :id => 228, :type_id => 5, :full_name => 'ワッキー', :short_name => 'ワッキー', :valid_st => 1 },

  { :id => 229, :type_id => 6, :full_name => 'シュテーゲン', :short_name => 'シュテーゲン', :valid_st => 1 },
  { :id => 230, :type_id => 6, :full_name => 'スビサレッタ', :short_name => 'スビサレッタ', :valid_st => 1 },
  { :id => 231, :type_id => 6, :full_name => 'バロッソ', :short_name => 'バロッソ', :valid_st => 1 },
  { :id => 232, :type_id => 6, :full_name => 'ビクトール・バイーア', :short_name => 'V・バイーア', :valid_st => 1 },
  { :id => 233, :type_id => 6, :full_name => 'ビクトール・バルデス', :short_name => 'V・バルデス', :valid_st => 1 },
  { :id => 234, :type_id => 6, :full_name => 'ブラボ', :short_name => 'ブラボ', :valid_st => 1 },
  { :id => 235, :type_id => 6, :full_name => 'ヘスプ', :short_name => 'ヘスプ', :valid_st => 1 },
  { :id => 236, :type_id => 6, :full_name => 'アドリアーノ・コレイア', :short_name => 'A・コレイア', :valid_st => 1 },
  { :id => 237, :type_id => 6, :full_name => 'アビダル', :short_name => 'アビダル', :valid_st => 1 },
  { :id => 238, :type_id => 6, :full_name => 'アベラルド', :short_name => 'アベラルド', :valid_st => 1 },
  { :id => 239, :type_id => 6, :full_name => 'ラモン・アレサンコ', :short_name => 'アレサンコ', :valid_st => 1 },
  { :id => 240, :type_id => 6, :full_name => 'オレゲール・プレサス', :short_name => 'オレゲール', :valid_st => 1 },
  { :id => 241, :type_id => 6, :full_name => 'ガブリエル・ミリート', :short_name => 'G・ミリート', :valid_st => 1 },
  { :id => 242, :type_id => 6, :full_name => 'ロナルド・クーマン', :short_name => 'クーマン', :valid_st => 1 },
  { :id => 243, :type_id => 6, :full_name => 'ザンブロッタ', :short_name => 'ザンブロッタ', :valid_st => 1 },
  { :id => 244, :type_id => 6, :full_name => 'シウヴィーニョ', :short_name => 'シウヴィーニョ', :valid_st => 1 },
  { :id => 245, :type_id => 6, :full_name => 'ファン・ブロンクホルスト', :short_name => 'ジオ', :valid_st => 1 },
  { :id => 246, :type_id => 6, :full_name => 'ジョルディ・アルバ', :short_name => 'J・アルバ', :valid_st => 1 },
  { :id => 247, :type_id => 6, :full_name => 'セルジ・バルファン', :short_name => 'S・バルファン', :valid_st => 1 },
  { :id => 248, :type_id => 6, :full_name => 'ダニエウ・アウベス', :short_name => 'D・アウベス', :valid_st => 1 },
  { :id => 249, :type_id => 6, :full_name => 'フランク・デ・ブール', :short_name => 'デ・ブール', :valid_st => 1 },
  { :id => 250, :type_id => 6, :full_name => 'テュラム', :short_name => 'テュラム', :valid_st => 1 },
  { :id => 251, :type_id => 6, :full_name => 'ミゲル・アンヘル・ナダル', :short_name => 'ナダル', :valid_st => 1 },
  { :id => 252, :type_id => 6, :full_name => 'ナンド', :short_name => 'ナンド', :valid_st => 1 },
  { :id => 253, :type_id => 6, :full_name => 'ピケ', :short_name => 'ピケ', :valid_st => 1 },
  { :id => 254, :type_id => 6, :full_name => 'フェルメーレン', :short_name => 'フェルメーレン', :valid_st => 1 },
  { :id => 255, :type_id => 6, :full_name => 'アルベルト・フェレール', :short_name => 'フェレール', :valid_st => 1 },
  { :id => 256, :type_id => 6, :full_name => 'プジョル', :short_name => 'プジョル', :valid_st => 1 },
  { :id => 257, :type_id => 6, :full_name => 'ジュリアーノ・ベレッチ', :short_name => 'ベレッチ', :valid_st => 1 },
  { :id => 258, :type_id => 6, :full_name => 'ゲオルゲ・ポペスク', :short_name => 'ポペスク', :valid_st => 1 },
  { :id => 259, :type_id => 6, :full_name => 'マクスウェル', :short_name => 'マクスウェル', :valid_st => 1 },
  { :id => 260, :type_id => 6, :full_name => 'マスチェラーノ', :short_name => 'マスチェラーノ', :valid_st => 1 },
  { :id => 261, :type_id => 6, :full_name => 'マテュー', :short_name => 'マテュー', :valid_st => 1 },
  { :id => 262, :type_id => 6, :full_name => 'ラファエル・マルケス', :short_name => 'マルケス', :valid_st => 1 },
  { :id => 263, :type_id => 6, :full_name => 'ミゲリ', :short_name => 'ミゲリ', :valid_st => 1 },
  { :id => 264, :type_id => 6, :full_name => 'アモール', :short_name => 'アモール', :valid_st => 1 },
  { :id => 265, :type_id => 6, :full_name => 'イニエスタ', :short_name => 'イニエスタ', :valid_st => 1 },
  { :id => 266, :type_id => 6, :full_name => 'エウセビオ', :short_name => 'エウセビオ', :valid_st => 1 },
  { :id => 267, :type_id => 6, :full_name => 'エジミウソン', :short_name => 'エジミウソン', :valid_st => 1 },
  { :id => 268, :type_id => 6, :full_name => 'ガブリ', :short_name => 'ガブリ', :valid_st => 1 },
  { :id => 269, :type_id => 6, :full_name => 'グアルディオラ', :short_name => 'グアルディオラ', :valid_st => 1 },
  { :id => 270, :type_id => 6, :full_name => 'ゴイコエチェア', :short_name => 'ゴイコエチェア', :valid_st => 1 },
  { :id => 271, :type_id => 6, :full_name => 'コクー', :short_name => 'コクー', :valid_st => 1 },
  { :id => 272, :type_id => 6, :full_name => 'ジェラール・ロペス', :short_name => 'G・ロペス', :valid_st => 1 },
  { :id => 273, :type_id => 6, :full_name => 'ジオヴァンニ', :short_name => 'ジオヴァンニ', :valid_st => 1 },
  { :id => 274, :type_id => 6, :full_name => 'シャビ', :short_name => 'シャビ', :valid_st => 1 },
  { :id => 275, :type_id => 6, :full_name => 'ベルント・シュスター', :short_name => 'シュスター', :valid_st => 1 },
  { :id => 276, :type_id => 6, :full_name => 'セイドゥ・ケイタ', :short_name => 'S・ケイタ', :valid_st => 1 },
  { :id => 277, :type_id => 6, :full_name => 'セスク', :short_name => 'セスク', :valid_st => 1 },
  { :id => 278, :type_id => 6, :full_name => 'アルベルト・セラーデス', :short_name => 'セラーデス', :valid_st => 1 },
  { :id => 279, :type_id => 6, :full_name => 'ダーヴィッツ', :short_name => 'ダーヴィッツ', :valid_st => 1 },
  { :id => 280, :type_id => 6, :full_name => 'チアゴ・モッタ', :short_name => 'T・モッタ', :valid_st => 1 },
  { :id => 281, :type_id => 6, :full_name => 'デコ', :short_name => 'デコ', :valid_st => 1 },
  { :id => 282, :type_id => 6, :full_name => 'デ・ラ・ペーニャ', :short_name => 'デラペーニャ', :valid_st => 1 },
  { :id => 283, :type_id => 6, :full_name => 'バケーロ', :short_name => 'バケーロ', :valid_st => 1 },
  { :id => 284, :type_id => 6, :full_name => 'ゲオルゲ・ハジ', :short_name => 'ハジ', :valid_st => 1 },
  { :id => 285, :type_id => 6, :full_name => 'ブスケツ', :short_name => 'ブスケツ', :valid_st => 1 },
  { :id => 286, :type_id => 6, :full_name => 'プロシネチキ', :short_name => 'プロシネチキ', :valid_st => 1 },
  { :id => 287, :type_id => 6, :full_name => 'ベギリスタイン', :short_name => 'ベギリスタイン', :valid_st => 1 },
  { :id => 288, :type_id => 6, :full_name => 'ヤヤ・トゥーレ', :short_name => 'ヤヤ・トゥーレ', :valid_st => 1 },
  { :id => 289, :type_id => 6, :full_name => 'ラキティッチ', :short_name => 'ラキティッチ', :valid_st => 1 },
  { :id => 290, :type_id => 6, :full_name => 'リバウド', :short_name => 'リバウド', :valid_st => 1 },
  { :id => 291, :type_id => 6, :full_name => 'ルイス・エンリケ', :short_name => 'L・エンリケ', :valid_st => 1 },
  { :id => 292, :type_id => 6, :full_name => 'アレクシス・サンチェス', :short_name => 'A・サンチェス', :valid_st => 1 },
  { :id => 293, :type_id => 6, :full_name => 'アンリ', :short_name => 'アンリ', :valid_st => 1 },
  { :id => 294, :type_id => 6, :full_name => 'イブラヒモビッチ', :short_name => 'イブラヒモビッチ', :valid_st => 1 },
  { :id => 295, :type_id => 6, :full_name => 'エトー', :short_name => 'エトー', :valid_st => 1 },
  { :id => 296, :type_id => 6, :full_name => 'クライファート', :short_name => 'クライファート', :valid_st => 1 },
  { :id => 297, :type_id => 6, :full_name => 'サビオラ', :short_name => 'サビオラ', :valid_st => 1 },
  { :id => 298, :type_id => 6, :full_name => 'サリナス', :short_name => 'サリナス', :valid_st => 1 },
  { :id => 299, :type_id => 6, :full_name => 'リュドヴィク・ジュリ', :short_name => 'ジュリ', :valid_st => 1 },
  { :id => 300, :type_id => 6, :full_name => 'スアレス', :short_name => 'スアレス', :valid_st => 1 },
  { :id => 301, :type_id => 6, :full_name => 'ストイチコフ', :short_name => 'ストイチコフ', :valid_st => 1 },
  { :id => 302, :type_id => 6, :full_name => 'ネイマール', :short_name => 'ネイマール', :valid_st => 1 },
  { :id => 303, :type_id => 6, :full_name => 'ビジャ', :short_name => 'ビジャ', :valid_st => 1 },
  { :id => 304, :type_id => 6, :full_name => 'フィーゴ', :short_name => 'フィーゴ', :valid_st => 1 },
  { :id => 305, :type_id => 6, :full_name => 'ペドロ', :short_name => 'ペドロ', :valid_st => 1 },
  { :id => 306, :type_id => 6, :full_name => 'メッシ', :short_name => 'メッシ', :valid_st => 1 },
  { :id => 307, :type_id => 6, :full_name => 'ラウドルップ', :short_name => 'ラウドルップ', :valid_st => 1 },
  { :id => 308, :type_id => 6, :full_name => 'ロナウジーニョ', :short_name => 'ロナウジーニョ', :valid_st => 1 },
  { :id => 309, :type_id => 6, :full_name => 'ロナウド', :short_name => 'ロナウド', :valid_st => 1 },
  { :id => 310, :type_id => 6, :full_name => 'ロマーリオ', :short_name => 'ロマーリオ', :valid_st => 1 },

  { :id => 311, :type_id => 7, :full_name => 'イブラヒモビッチ', :short_name => 'イブラヒモビッチ', :valid_st => 1 },
  { :id => 312, :type_id => 7, :full_name => 'インザーギ', :short_name => 'インザーギ', :valid_st => 1 },
  { :id => 313, :type_id => 7, :full_name => 'エムベイェ・ニアン', :short_name => 'M・ニアン', :valid_st => 1 },
  { :id => 314, :type_id => 7, :full_name => 'エル・シャーラウィ', :short_name => 'エル・シャーラウィ', :valid_st => 1 },
  { :id => 315, :type_id => 7, :full_name => 'カッサーノ', :short_name => 'カッサーノ', :valid_st => 1 },
  { :id => 316, :type_id => 7, :full_name => 'クライファート', :short_name => 'クライファート', :valid_st => 1 },
  { :id => 317, :type_id => 7, :full_name => 'クレスポ', :short_name => 'クレスポ', :valid_st => 1 },
  { :id => 318, :type_id => 7, :full_name => 'サビチェビッチ', :short_name => 'サビチェビッチ', :valid_st => 1 },
  { :id => 319, :type_id => 7, :full_name => 'シェフチェンコ', :short_name => 'シェフチェンコ', :valid_st => 1 },
  { :id => 320, :type_id => 7, :full_name => 'ジョージ・ウェア', :short_name => 'G・ウェア', :valid_st => 1 },
  { :id => 321, :type_id => 7, :full_name => 'ジラルディーノ', :short_name => 'ジラルディーノ', :valid_st => 1 },
  { :id => 322, :type_id => 7, :full_name => 'ディ・カーニオ', :short_name => 'ディ・カーニオ', :valid_st => 1 },
  { :id => 323, :type_id => 7, :full_name => 'トマソン', :short_name => 'トマソン', :valid_st => 1 },
  { :id => 324, :type_id => 7, :full_name => 'パッツィーニ', :short_name => 'パッツィーニ', :valid_st => 1 },
  { :id => 325, :type_id => 7, :full_name => 'パト', :short_name => 'パト', :valid_st => 1 },
  { :id => 326, :type_id => 7, :full_name => 'パパン', :short_name => 'パパン', :valid_st => 1 },
  { :id => 327, :type_id => 7, :full_name => 'バロテッリ', :short_name => 'バロテッリ', :valid_st => 1 },
  { :id => 328, :type_id => 7, :full_name => 'ビアホフ', :short_name => 'ビアホフ', :valid_st => 1 },
  { :id => 329, :type_id => 7, :full_name => 'ファン・バステン', :short_name => 'ファン・バステン', :valid_st => 1 },
  { :id => 330, :type_id => 7, :full_name => 'フンテラール', :short_name => 'フンテラール', :valid_st => 1 },
  { :id => 331, :type_id => 7, :full_name => 'ボージャン', :short_name => 'ボージャン', :valid_st => 1 },
  { :id => 332, :type_id => 7, :full_name => 'ホセ・マリ', :short_name => 'ホセ・マリ', :valid_st => 1 },
  { :id => 333, :type_id => 7, :full_name => 'ボリエッロ', :short_name => 'ボリエッロ', :valid_st => 1 },
  { :id => 334, :type_id => 7, :full_name => '本田圭佑', :short_name => '本田', :valid_st => 1 },
  { :id => 335, :type_id => 7, :full_name => 'マッサーロ', :short_name => 'マッサーロ', :valid_st => 1 },
  { :id => 336, :type_id => 7, :full_name => 'マルコ・シモーネ', :short_name => 'M・シモーネ', :valid_st => 1 },
  { :id => 337, :type_id => 7, :full_name => 'メネズ', :short_name => 'メネズ', :valid_st => 1 },
  { :id => 338, :type_id => 7, :full_name => 'リカルド・オリヴェイラ', :short_name => 'R・オリヴェイラ', :valid_st => 1 },
  { :id => 339, :type_id => 7, :full_name => 'ロナウジーニョ', :short_name => 'ロナウジーニョ', :valid_st => 1 },
  { :id => 340, :type_id => 7, :full_name => 'ロナウド', :short_name => 'ロナウド', :valid_st => 1 },
  { :id => 341, :type_id => 7, :full_name => 'ロビーニョ', :short_name => 'ロビーニョ', :valid_st => 1 },
  { :id => 342, :type_id => 7, :full_name => 'ロベルト・バッジョ', :short_name => 'R・バッジョ', :valid_st => 1 },
  { :id => 343, :type_id => 7, :full_name => 'アルベリゴ・エヴァーニ', :short_name => 'A・エヴァーニ', :valid_st => 1 },
  { :id => 344, :type_id => 7, :full_name => 'アルベルティーニ', :short_name => 'アルベルティーニ', :valid_st => 1 },
  { :id => 345, :type_id => 7, :full_name => 'アンチェロッティ', :short_name => 'アンチェロッティ', :valid_st => 1 },
  { :id => 346, :type_id => 7, :full_name => 'アンブロジーニ', :short_name => 'アンブロジーニ', :valid_st => 1 },
  { :id => 347, :type_id => 7, :full_name => 'カカ', :short_name => 'カカ', :valid_st => 1 },
  { :id => 348, :type_id => 7, :full_name => 'ガットゥーゾ', :short_name => 'ガットゥーゾ', :valid_st => 1 },
  { :id => 349, :type_id => 7, :full_name => 'コロンボ', :short_name => 'コロンボ', :valid_st => 1 },
  { :id => 350, :type_id => 7, :full_name => 'セードルフ', :short_name => 'セードルフ', :valid_st => 1 },
  { :id => 351, :type_id => 7, :full_name => 'ダーヴィッツ', :short_name => 'ダーヴィッツ', :valid_st => 1 },
  { :id => 352, :type_id => 7, :full_name => 'デサイー', :short_name => 'デサイー', :valid_st => 1 },
  { :id => 353, :type_id => 7, :full_name => 'デ・ヨング', :short_name => 'デ・ヨング', :valid_st => 1 },
  { :id => 354, :type_id => 7, :full_name => 'ドナドーニ', :short_name => 'ドナドーニ', :valid_st => 1 },
  { :id => 355, :type_id => 7, :full_name => 'ノチェリーノ', :short_name => 'ノチェリーノ', :valid_st => 1 },
  { :id => 356, :type_id => 7, :full_name => 'ピルロ', :short_name => 'ピルロ', :valid_st => 1 },
  { :id => 357, :type_id => 7, :full_name => 'ファン・ボメル', :short_name => 'V・ボメル', :valid_st => 1 },
  { :id => 358, :type_id => 7, :full_name => 'フラミニ', :short_name => 'フラミニ', :valid_st => 1 },
  { :id => 359, :type_id => 7, :full_name => 'フリット', :short_name => 'フリット', :valid_st => 1 },
  { :id => 360, :type_id => 7, :full_name => 'ブロッキ', :short_name => 'ブロッキ', :valid_st => 1 },
  { :id => 361, :type_id => 7, :full_name => 'ベッカム', :short_name => 'ベッカム', :valid_st => 1 },
  { :id => 362, :type_id => 7, :full_name => 'ボアテング', :short_name => 'ボアテング', :valid_st => 1 },
  { :id => 363, :type_id => 7, :full_name => 'ボバン', :short_name => 'ボバン', :valid_st => 1 },
  { :id => 364, :type_id => 7, :full_name => 'ムンタリ', :short_name => 'ムンタリ', :valid_st => 1 },
  { :id => 365, :type_id => 7, :full_name => 'モントリーヴォ', :short_name => 'モントリーヴォ', :valid_st => 1 },
  { :id => 366, :type_id => 7, :full_name => 'ライカールト', :short_name => 'ライカールト', :valid_st => 1 },
  { :id => 367, :type_id => 7, :full_name => 'リバウド', :short_name => 'リバウド', :valid_st => 1 },
  { :id => 368, :type_id => 7, :full_name => 'ルイ・コスタ', :short_name => 'ルイ・コスタ', :valid_st => 1 },
  { :id => 369, :type_id => 7, :full_name => 'レオナルド', :short_name => 'レオナルド', :valid_st => 1 },
  { :id => 370, :type_id => 7, :full_name => 'レンティーニ', :short_name => 'レンティーニ', :valid_st => 1 },
  { :id => 371, :type_id => 7, :full_name => 'アバーテ', :short_name => 'アバーテ', :valid_st => 1 },
  { :id => 372, :type_id => 7, :full_name => 'アレックス', :short_name => 'アレックス', :valid_st => 1 },
  { :id => 373, :type_id => 7, :full_name => 'カハ・カラーゼ', :short_name => 'カハ・カラーゼ', :valid_st => 1 },
  { :id => 374, :type_id => 7, :full_name => 'カフー', :short_name => 'カフー', :valid_st => 1 },
  { :id => 375, :type_id => 7, :full_name => 'コスタクルタ', :short_name => 'コスタクルタ', :valid_st => 1 },
  { :id => 376, :type_id => 7, :full_name => 'コンスタン', :short_name => 'コンスタン', :valid_st => 1 },
  { :id => 377, :type_id => 7, :full_name => 'サパタ', :short_name => 'サパタ', :valid_st => 1 },
  { :id => 378, :type_id => 7, :full_name => 'ザンブロッタ', :short_name => 'ザンブロッタ', :valid_st => 1 },
  { :id => 379, :type_id => 7, :full_name => 'セルジーニョ', :short_name => 'セルジーニョ', :valid_st => 1 },
  { :id => 380, :type_id => 7, :full_name => 'マウロ・タソッティ', :short_name => 'タソッティ', :valid_st => 1 },
  { :id => 381, :type_id => 7, :full_name => 'ダリオ・シミッチ', :short_name => 'D・シミッチ', :valid_st => 1 },
  { :id => 382, :type_id => 7, :full_name => 'チアゴ・シウバ', :short_name => 'T・シウバ', :valid_st => 1 },
  { :id => 383, :type_id => 7, :full_name => 'デ・シリオ', :short_name => 'デ・シリオ', :valid_st => 1 },
  { :id => 384, :type_id => 7, :full_name => 'トーマス・ヘルヴェグ', :short_name => 'T・ヘルヴェグ', :valid_st => 1 },
  { :id => 385, :type_id => 7, :full_name => 'ネスタ', :short_name => 'ネスタ', :valid_st => 1 },
  { :id => 386, :type_id => 7, :full_name => 'パヌッチ', :short_name => 'パヌッチ', :valid_st => 1 },
  { :id => 387, :type_id => 7, :full_name => 'バレージ', :short_name => 'バレージ', :valid_st => 1 },
  { :id => 388, :type_id => 7, :full_name => 'フランチェスコ・ココ', :short_name => 'F・ココ', :valid_st => 1 },
  { :id => 389, :type_id => 7, :full_name => 'ホセ・チャモ', :short_name => 'ホセ・チャモ', :valid_st => 1 },
  { :id => 390, :type_id => 7, :full_name => 'ボネーラ', :short_name => 'ボネーラ', :valid_st => 1 },
  { :id => 391, :type_id => 7, :full_name => 'マリオ・ジェペス', :short_name => 'M・ジェペス', :valid_st => 1 },
  { :id => 392, :type_id => 7, :full_name => 'マルディーニ', :short_name => 'マルディーニ', :valid_st => 1 },
  { :id => 393, :type_id => 7, :full_name => 'マルティン・ラウルセン', :short_name => 'M・ラウルセン', :valid_st => 1 },
  { :id => 394, :type_id => 7, :full_name => 'メクセス', :short_name => 'メクセス', :valid_st => 1 },
  { :id => 395, :type_id => 7, :full_name => 'ヤープ・スタム', :short_name => 'J・スタム', :valid_st => 1 },
  { :id => 396, :type_id => 7, :full_name => 'ヤンクロフスキ', :short_name => 'ヤンクロフスキ', :valid_st => 1 },
  { :id => 397, :type_id => 7, :full_name => 'ラミ', :short_name => 'ラミ', :valid_st => 1 },
  { :id => 398, :type_id => 7, :full_name => 'ルイジ・サーラ', :short_name => 'L・サーラ', :valid_st => 1 },
  { :id => 399, :type_id => 7, :full_name => 'ルカ・アントニーニ', :short_name => 'L・アントニーニ', :valid_st => 1 },
  { :id => 400, :type_id => 7, :full_name => 'ロッキ・ジュニオール', :short_name => 'R・ジュニオール', :valid_st => 1 },
  { :id => 401, :type_id => 7, :full_name => 'アッビアーティ', :short_name => 'アッビアーティ', :valid_st => 1 },
  { :id => 402, :type_id => 7, :full_name => 'ジーダ', :short_name => 'ジーダ', :valid_st => 1 },
  { :id => 403, :type_id => 7, :full_name => 'ジョバンニ・ガッリ', :short_name => 'G・ガッリ', :valid_st => 1 },
  { :id => 404, :type_id => 7, :full_name => 'セバスティアーノ・ロッシ', :short_name => 'S・ロッシ', :valid_st => 1 },
  { :id => 405, :type_id => 7, :full_name => 'ディエゴ・ロペス', :short_name => 'D・ロペス', :valid_st => 1 },

  { :id => 406, :type_id => 8, :full_name => 'アラウージョ', :short_name => 'アラウージョ', :valid_st => 1 },
  { :id => 407, :type_id => 8, :full_name => 'ウィル', :short_name => 'ウィル', :valid_st => 1 },
  { :id => 408, :type_id => 8, :full_name => 'ウイルソン', :short_name => 'ウイルソン', :valid_st => 1 },
  { :id => 409, :type_id => 8, :full_name => 'ウェズレイ', :short_name => 'ウェズレイ', :valid_st => 1 },
  { :id => 410, :type_id => 8, :full_name => '宇佐美貴史', :short_name => '宇佐美貴史', :valid_st => 1 },
  { :id => 411, :type_id => 8, :full_name => 'エムボマ', :short_name => 'エムボマ', :valid_st => 1 },
  { :id => 412, :type_id => 8, :full_name => 'エメルソン', :short_name => 'エメルソン', :valid_st => 1 },
  { :id => 413, :type_id => 8, :full_name => '大久保嘉人', :short_name => '大久保嘉人', :valid_st => 1 },
  { :id => 414, :type_id => 8, :full_name => '大黒将志', :short_name => '大黒将志', :valid_st => 1 },
  { :id => 415, :type_id => 8, :full_name => '大迫勇也', :short_name => '大迫勇也', :valid_st => 1 },
  { :id => 416, :type_id => 8, :full_name => '岡崎慎司', :short_name => '岡崎慎司', :valid_st => 1 },
  { :id => 417, :type_id => 8, :full_name => '岡野雅行', :short_name => '岡野雅行', :valid_st => 1 },
  { :id => 418, :type_id => 8, :full_name => '川又堅碁', :short_name => '川又堅碁', :valid_st => 1 },
  { :id => 419, :type_id => 8, :full_name => '久保竜彦', :short_name => '久保竜彦', :valid_st => 1 },
  { :id => 420, :type_id => 8, :full_name => 'ケネディ', :short_name => 'ケネディ', :valid_st => 1 },
  { :id => 421, :type_id => 8, :full_name => '佐藤寿人', :short_name => '佐藤寿人', :valid_st => 1 },
  { :id => 422, :type_id => 8, :full_name => 'ジュニーニョ', :short_name => 'ジュニーニョ', :valid_st => 1 },
  { :id => 423, :type_id => 8, :full_name => 'ストイコビッチ', :short_name => 'ストイコビッチ', :valid_st => 1 },
  { :id => 424, :type_id => 8, :full_name => '高木琢也', :short_name => '高木琢也', :valid_st => 1 },
  { :id => 425, :type_id => 8, :full_name => '高原直泰', :short_name => '高原直泰', :valid_st => 1 },
  { :id => 426, :type_id => 8, :full_name => '武田修宏', :short_name => '武田修宏', :valid_st => 1 },
  { :id => 427, :type_id => 8, :full_name => 'ツゥット', :short_name => 'ツゥット', :valid_st => 1 },
  { :id => 428, :type_id => 8, :full_name => '豊田陽平', :short_name => '豊田陽平', :valid_st => 1 },
  { :id => 429, :type_id => 8, :full_name => '中山雅史', :short_name => '中山雅史', :valid_st => 1 },
  { :id => 430, :type_id => 8, :full_name => '西澤明訓', :short_name => '西澤明訓', :valid_st => 1 },
  { :id => 431, :type_id => 8, :full_name => 'ハーフナー・マイク', :short_name => 'ハーフナー', :valid_st => 1 },
  { :id => 432, :type_id => 8, :full_name => 'パトリック', :short_name => 'パトリック', :valid_st => 1 },
  { :id => 433, :type_id => 8, :full_name => 'バレー', :short_name => 'バレー', :valid_st => 1 },
  { :id => 434, :type_id => 8, :full_name => '黄善洪', :short_name => '黄善洪', :valid_st => 1 },
  { :id => 435, :type_id => 8, :full_name => '福田正博', :short_name => '福田正博', :valid_st => 1 },
  { :id => 436, :type_id => 8, :full_name => '前田遼一', :short_name => '前田遼一', :valid_st => 1 },
  { :id => 437, :type_id => 8, :full_name => 'マグノ・アウベス', :short_name => 'マグノ・アウベス', :valid_st => 1 },
  { :id => 438, :type_id => 8, :full_name => 'マルキーニョス', :short_name => 'マルキーニョス', :valid_st => 1 },
  { :id => 439, :type_id => 8, :full_name => 'マルケス', :short_name => 'マルケス', :valid_st => 1 },
  { :id => 440, :type_id => 8, :full_name => '三浦知良', :short_name => '三浦知良', :valid_st => 1 },
  { :id => 441, :type_id => 8, :full_name => '森島寛晃', :short_name => '森島寛晃', :valid_st => 1 },
  { :id => 442, :type_id => 8, :full_name => '柳沢敦', :short_name => '柳沢敦', :valid_st => 1 },
  { :id => 443, :type_id => 8, :full_name => 'ラモン・ディアス', :short_name => 'R・ディアス', :valid_st => 1 },
  { :id => 444, :type_id => 8, :full_name => 'ワシントン', :short_name => 'ワシントン', :valid_st => 1 },
  { :id => 445, :type_id => 8, :full_name => '青山敏弘', :short_name => '青山敏弘', :valid_st => 1 },
  { :id => 446, :type_id => 8, :full_name => '阿部勇樹', :short_name => '阿部勇樹', :valid_st => 1 },
  { :id => 447, :type_id => 8, :full_name => '石川直宏', :short_name => '石川直宏', :valid_st => 1 },
  { :id => 448, :type_id => 8, :full_name => '伊東輝悦', :short_name => '伊東輝悦', :valid_st => 1 },
  { :id => 449, :type_id => 8, :full_name => '稲本潤一', :short_name => '稲本潤一', :valid_st => 1 },
  { :id => 450, :type_id => 8, :full_name => '遠藤保仁', :short_name => '遠藤保仁', :valid_st => 1 },
  { :id => 451, :type_id => 8, :full_name => '小笠原満男', :short_name => '小笠原満男', :valid_st => 1 },
  { :id => 452, :type_id => 8, :full_name => '小川佳純', :short_name => '小川佳純', :valid_st => 1 },
  { :id => 453, :type_id => 8, :full_name => '奥大介', :short_name => '奥大介', :valid_st => 1 },
  { :id => 454, :type_id => 8, :full_name => '小野伸二', :short_name => '小野伸二', :valid_st => 1 },
  { :id => 455, :type_id => 8, :full_name => '柿谷曜一朗', :short_name => '柿谷曜一朗', :valid_st => 1 },
  { :id => 456, :type_id => 8, :full_name => '北澤豪', :short_name => '北澤豪', :valid_st => 1 },
  { :id => 457, :type_id => 8, :full_name => '清武弘嗣', :short_name => '清武弘嗣', :valid_st => 1 },
  { :id => 458, :type_id => 8, :full_name => '澤登正朗', :short_name => '澤登正朗', :valid_st => 1 },
  { :id => 459, :type_id => 8, :full_name => '三都主', :short_name => '三都主', :valid_st => 1 },
  { :id => 460, :type_id => 8, :full_name => 'サントス', :short_name => 'サントス', :valid_st => 1 },
  { :id => 461, :type_id => 8, :full_name => '柴崎岳', :short_name => '柴崎岳', :valid_st => 1 },
  { :id => 462, :type_id => 8, :full_name => 'ジェルジーニョ', :short_name => 'ジェルジーニョ', :valid_st => 1 },
  { :id => 463, :type_id => 8, :full_name => 'ジョルジ・ワグネル', :short_name => 'J・ワグネル', :valid_st => 1 },
  { :id => 464, :type_id => 8, :full_name => '鈴木啓太', :short_name => '鈴木啓太', :valid_st => 1 },
  { :id => 465, :type_id => 8, :full_name => '高萩洋次郎', :short_name => '高萩洋次郎', :valid_st => 1 },
  { :id => 466, :type_id => 8, :full_name => '谷口博之', :short_name => '谷口博之', :valid_st => 1 },
  { :id => 467, :type_id => 8, :full_name => 'ダニルソン', :short_name => 'ダニルソン', :valid_st => 1 },
  { :id => 468, :type_id => 8, :full_name => 'ドゥンガ', :short_name => 'ドゥンガ', :valid_st => 1 },
  { :id => 469, :type_id => 8, :full_name => '中田浩二', :short_name => '中田浩二', :valid_st => 1 },
  { :id => 470, :type_id => 8, :full_name => '中田英寿', :short_name => '中田英寿', :valid_st => 1 },
  { :id => 471, :type_id => 8, :full_name => '中村憲剛', :short_name => '中村憲剛', :valid_st => 1 },
  { :id => 472, :type_id => 8, :full_name => '中村俊輔', :short_name => '中村俊輔', :valid_st => 1 },
  { :id => 473, :type_id => 8, :full_name => '名波浩', :short_name => '名波浩', :valid_st => 1 },
  { :id => 474, :type_id => 8, :full_name => '長谷部誠', :short_name => '長谷部誠', :valid_st => 1 },
  { :id => 475, :type_id => 8, :full_name => '服部年宏', :short_name => '服部年宏', :valid_st => 1 },
  { :id => 476, :type_id => 8, :full_name => 'ビスマルク', :short_name => 'ビスマルク', :valid_st => 1 },
  { :id => 477, :type_id => 8, :full_name => 'フェルナンジーニョ', :short_name => 'フェルナンジーニョ', :valid_st => 1 },
  { :id => 478, :type_id => 8, :full_name => '福西崇史', :short_name => '福西崇史', :valid_st => 1 },
  { :id => 479, :type_id => 8, :full_name => '藤田俊哉', :short_name => '藤田俊哉', :valid_st => 1 },
  { :id => 480, :type_id => 8, :full_name => '藤本淳吾', :short_name => '藤本淳吾', :valid_st => 1 },
  { :id => 481, :type_id => 8, :full_name => '古橋達弥', :short_name => '古橋達弥', :valid_st => 1 },
  { :id => 482, :type_id => 8, :full_name => 'ベッチーニョ', :short_name => 'ベッチーニョ', :valid_st => 1 },
  { :id => 483, :type_id => 8, :full_name => '本田泰人', :short_name => '本田泰人', :valid_st => 1 },
  { :id => 484, :type_id => 8, :full_name => 'ポンテ', :short_name => 'ポンテ', :valid_st => 1 },
  { :id => 485, :type_id => 8, :full_name => '前園真聖', :short_name => '前園真聖', :valid_st => 1 },
  { :id => 486, :type_id => 8, :full_name => 'マルシオ・リシャルデス', :short_name => 'M・リシャルデス', :valid_st => 1 },
  { :id => 487, :type_id => 8, :full_name => '明神智和', :short_name => '明神智和', :valid_st => 1 },
  { :id => 488, :type_id => 8, :full_name => '武藤嘉紀', :short_name => '武藤嘉紀', :valid_st => 1 },
  { :id => 489, :type_id => 8, :full_name => '山口螢', :short_name => '山口螢', :valid_st => 1 },
  { :id => 490, :type_id => 8, :full_name => '山口素弘', :short_name => '山口素弘', :valid_st => 1 },
  { :id => 491, :type_id => 8, :full_name => 'ラモス瑠偉', :short_name => 'ラモス瑠偉', :valid_st => 1 },
  { :id => 492, :type_id => 8, :full_name => 'レアンドロ・ドミンゲス', :short_name => 'L・ドミンゲス', :valid_st => 1 },
  { :id => 493, :type_id => 8, :full_name => 'レオ・シルバ', :short_name => 'レオ・シルバ', :valid_st => 1 },
  { :id => 494, :type_id => 8, :full_name => '秋田豊', :short_name => '秋田豊', :valid_st => 1 },
  { :id => 495, :type_id => 8, :full_name => '井原正巳', :short_name => '井原正巳', :valid_st => 1 },
  { :id => 496, :type_id => 8, :full_name => '岩政大樹', :short_name => '岩政大樹', :valid_st => 1 },
  { :id => 497, :type_id => 8, :full_name => '内田篤人', :short_name => '内田篤人', :valid_st => 1 },
  { :id => 498, :type_id => 8, :full_name => '大岩剛', :short_name => '大岩剛', :valid_st => 1 },
  { :id => 499, :type_id => 8, :full_name => '太田宏介', :short_name => '太田宏介', :valid_st => 1 },
  { :id => 500, :type_id => 8, :full_name => '大野俊三', :short_name => '大野俊三', :valid_st => 1 },
  { :id => 501, :type_id => 8, :full_name => '加地亮', :short_name => '加地亮', :valid_st => 1 },
  { :id => 502, :type_id => 8, :full_name => '駒野友一', :short_name => '駒野友一', :valid_st => 1 },
  { :id => 503, :type_id => 8, :full_name => '近藤直也', :short_name => '近藤直也', :valid_st => 1 },
  { :id => 504, :type_id => 8, :full_name => '斉藤俊秀', :short_name => '斉藤俊秀', :valid_st => 1 },
  { :id => 505, :type_id => 8, :full_name => '酒井宏樹', :short_name => '酒井宏樹', :valid_st => 1 },
  { :id => 506, :type_id => 8, :full_name => '塩谷司', :short_name => '塩谷司', :valid_st => 1 },
  { :id => 507, :type_id => 8, :full_name => '鈴木秀人', :short_name => '鈴木秀人', :valid_st => 1 },
  { :id => 508, :type_id => 8, :full_name => '鈴木正治', :short_name => '鈴木正治', :valid_st => 1 },
  { :id => 509, :type_id => 8, :full_name => 'ストヤノフ', :short_name => 'ストヤノフ', :valid_st => 1 },
  { :id => 510, :type_id => 8, :full_name => '相馬直樹', :short_name => '相馬直樹', :valid_st => 1 },
  { :id => 511, :type_id => 8, :full_name => '田中誠', :short_name => '田中誠', :valid_st => 1 },
  { :id => 512, :type_id => 8, :full_name => '坪井慶介', :short_name => '坪井慶介', :valid_st => 1 },
  { :id => 513, :type_id => 8, :full_name => '闘莉王', :short_name => '闘莉王', :valid_st => 1 },
  { :id => 514, :type_id => 8, :full_name => 'ドゥトラ', :short_name => 'ドゥトラ', :valid_st => 1 },
  { :id => 515, :type_id => 8, :full_name => '中澤佑二', :short_name => '中澤佑二', :valid_st => 1 },
  { :id => 516, :type_id => 8, :full_name => '長友佑都', :short_name => '長友佑都', :valid_st => 1 },
  { :id => 517, :type_id => 8, :full_name => '那須大亮', :short_name => '那須大亮', :valid_st => 1 },
  { :id => 518, :type_id => 8, :full_name => '名塚善寛', :short_name => '名塚善寛', :valid_st => 1 },
  { :id => 519, :type_id => 8, :full_name => '名良橋晃', :short_name => '名良橋晃', :valid_st => 1 },
  { :id => 520, :type_id => 8, :full_name => '柱谷哲二', :short_name => '柱谷哲二', :valid_st => 1 },
  { :id => 521, :type_id => 8, :full_name => 'ブッフバルト', :short_name => 'ブッフバルト', :valid_st => 1 },
  { :id => 522, :type_id => 8, :full_name => 'ペレイラ', :short_name => 'ペレイラ', :valid_st => 1 },
  { :id => 523, :type_id => 8, :full_name => '堀池巧', :short_name => '堀池巧', :valid_st => 1 },
  { :id => 524, :type_id => 8, :full_name => '洪明甫', :short_name => '洪明甫', :valid_st => 1 },
  { :id => 525, :type_id => 8, :full_name => '槙野智章', :short_name => '槙野智章', :valid_st => 1 },
  { :id => 526, :type_id => 8, :full_name => '増川隆洋', :short_name => '増川隆洋', :valid_st => 1 },
  { :id => 527, :type_id => 8, :full_name => '松田直樹', :short_name => '松田直樹', :valid_st => 1 },
  { :id => 528, :type_id => 8, :full_name => '水本裕貴', :short_name => '水本裕貴', :valid_st => 1 },
  { :id => 529, :type_id => 8, :full_name => '森岡隆三', :short_name => '森岡隆三', :valid_st => 1 },
  { :id => 530, :type_id => 8, :full_name => '森重真人', :short_name => '森重真人', :valid_st => 1 },
  { :id => 531, :type_id => 8, :full_name => '山口智', :short_name => '山口智', :valid_st => 1 },
  { :id => 532, :type_id => 8, :full_name => 'ヴァン・ズワム', :short_name => 'ヴァン・ズワム', :valid_st => 1 },
  { :id => 533, :type_id => 8, :full_name => '大神友明', :short_name => '大神友明', :valid_st => 1 },
  { :id => 534, :type_id => 8, :full_name => '川口能活', :short_name => '川口能活', :valid_st => 1 },
  { :id => 535, :type_id => 8, :full_name => '川島永嗣', :short_name => '川島永嗣', :valid_st => 1 },
  { :id => 536, :type_id => 8, :full_name => '菊池新吉', :short_name => '菊池新吉', :valid_st => 1 },
  { :id => 537, :type_id => 8, :full_name => '真田雅則', :short_name => '真田雅則', :valid_st => 1 },
  { :id => 538, :type_id => 8, :full_name => '曽ヶ端準', :short_name => '曽ヶ端準', :valid_st => 1 },
  { :id => 539, :type_id => 8, :full_name => '高桑大二朗', :short_name => '高桑大二朗', :valid_st => 1 },
  { :id => 540, :type_id => 8, :full_name => '都築龍太', :short_name => '都築龍太', :valid_st => 1 },
  { :id => 541, :type_id => 8, :full_name => '土肥洋一', :short_name => '土肥洋一', :valid_st => 1 },
  { :id => 542, :type_id => 8, :full_name => '楢崎正剛', :short_name => '楢崎正剛', :valid_st => 1 },
  { :id => 543, :type_id => 8, :full_name => '西川周作', :short_name => '西川周作', :valid_st => 1 },
  { :id => 544, :type_id => 8, :full_name => '松永成立', :short_name => '松永成立', :valid_st => 1 },
  { :id => 545, :type_id => 8, :full_name => '吉田宗弘', :short_name => '吉田宗弘', :valid_st => 1 },

  { :id => 546, :type_id => 9, :full_name => 'アラン・スミス', :short_name => 'A・スミス', :valid_st => 1 },
  { :id => 547, :type_id => 9, :full_name => 'アンディ・コール', :short_name => 'A・コール', :valid_st => 1 },
  { :id => 548, :type_id => 9, :full_name => 'ウェルベック', :short_name => 'ウェルベック', :valid_st => 1 },
  { :id => 549, :type_id => 9, :full_name => 'ハビエル・エルナンデス', :short_name => 'エルナンデス', :valid_st => 1 },
  { :id => 550, :type_id => 9, :full_name => 'オーウェン', :short_name => 'オーウェン', :valid_st => 1 },
  { :id => 551, :type_id => 9, :full_name => 'カントナ', :short_name => 'カントナ', :valid_st => 1 },
  { :id => 552, :type_id => 9, :full_name => 'クリスティアーノ・ロナウド', :short_name => 'C・ロナウド', :valid_st => 1 },
  { :id => 553, :type_id => 9, :full_name => 'サハ', :short_name => 'サハ', :valid_st => 1 },
  { :id => 554, :type_id => 9, :full_name => 'シェリンガム', :short_name => 'シェリンガム', :valid_st => 1 },
  { :id => 555, :type_id => 9, :full_name => 'スールシャール', :short_name => 'スールシャール', :valid_st => 1 },
  { :id => 556, :type_id => 9, :full_name => 'ディ・マリア', :short_name => 'ディ・マリア', :valid_st => 1 },
  { :id => 557, :type_id => 9, :full_name => 'テベス', :short_name => 'テベス', :valid_st => 1 },
  { :id => 558, :type_id => 9, :full_name => 'ドワイト・ヨーク', :short_name => 'D・ヨーク', :valid_st => 1 },
  { :id => 559, :type_id => 9, :full_name => 'ファルカオ', :short_name => 'ファルカオ', :valid_st => 1 },
  { :id => 560, :type_id => 9, :full_name => 'ファン・ニステルローイ', :short_name => 'V・ニステルローイ', :valid_st => 1 },
  { :id => 561, :type_id => 9, :full_name => 'ファン・ペルシ', :short_name => 'V・ペルシ', :valid_st => 1 },
  { :id => 562, :type_id => 9, :full_name => 'フォルラン', :short_name => 'フォルラン', :valid_st => 1 },
  { :id => 563, :type_id => 9, :full_name => 'ベルバトフ', :short_name => 'ベルバトフ', :valid_st => 1 },
  { :id => 564, :type_id => 9, :full_name => 'ホワイトサイド', :short_name => 'ホワイトサイド', :valid_st => 1 },
  { :id => 565, :type_id => 9, :full_name => 'マーク・ヒューズ', :short_name => 'M・ヒューズ', :valid_st => 1 },
  { :id => 566, :type_id => 9, :full_name => 'ブライアン・マクレアー', :short_name => 'マクレアー', :valid_st => 1 },
  { :id => 567, :type_id => 9, :full_name => 'ルーニー', :short_name => 'ルーニー', :valid_st => 1 },
  { :id => 568, :type_id => 9, :full_name => 'アシュリー・ヤング', :short_name => 'A・ヤング', :valid_st => 1 },
  { :id => 569, :type_id => 9, :full_name => 'エレーラ', :short_name => 'エレーラ', :valid_st => 1 },
  { :id => 570, :type_id => 9, :full_name => '香川真司', :short_name => '香川真司', :valid_st => 1 },
  { :id => 571, :type_id => 9, :full_name => 'カンチェルスキス', :short_name => 'カンチェルスキス', :valid_st => 1 },
  { :id => 572, :type_id => 9, :full_name => 'キーラン・リチャードソン', :short_name => 'K・リチャードソン', :valid_st => 1 },
  { :id => 573, :type_id => 9, :full_name => 'ギグス', :short_name => 'ギグス', :valid_st => 1 },
  { :id => 574, :type_id => 9, :full_name => 'キャリック', :short_name => 'キャリック', :valid_st => 1 },
  { :id => 575, :type_id => 9, :full_name => 'クレヴァリー', :short_name => 'クレヴァリー', :valid_st => 1 },
  { :id => 576, :type_id => 9, :full_name => 'ゴードン・ストラカン', :short_name => 'G・ストラカン', :valid_st => 1 },
  { :id => 577, :type_id => 9, :full_name => 'ジェンバ＝ジェンバ', :short_name => 'ジェンバ＝ジェンバ', :valid_st => 1 },
  { :id => 578, :type_id => 9, :full_name => 'スコールズ', :short_name => 'スコールズ', :valid_st => 1 },
  { :id => 579, :type_id => 9, :full_name => 'ナニ', :short_name => 'ナニ', :valid_st => 1 },
  { :id => 580, :type_id => 9, :full_name => 'ニッキー・バット', :short_name => 'N・バット', :valid_st => 1 },
  { :id => 581, :type_id => 9, :full_name => '朴智星', :short_name => '朴智星', :valid_st => 1 },
  { :id => 582, :type_id => 9, :full_name => 'バレンシア', :short_name => 'バレンシア', :valid_st => 1 },
  { :id => 583, :type_id => 9, :full_name => 'フアン・マタ', :short_name => 'フアン・マタ', :valid_st => 1 },
  { :id => 584, :type_id => 9, :full_name => 'フェライニ', :short_name => 'フェライニ', :valid_st => 1 },
  { :id => 585, :type_id => 9, :full_name => 'フォーチュン', :short_name => 'フォーチュン', :valid_st => 1 },
  { :id => 586, :type_id => 9, :full_name => 'ブライアン・ロブソン', :short_name => 'B・ロブソン', :valid_st => 1 },
  { :id => 587, :type_id => 9, :full_name => 'ブリント', :short_name => 'ブリント', :valid_st => 1 },
  { :id => 588, :type_id => 9, :full_name => 'ダレン・フレッチャー', :short_name => 'フレッチャー', :valid_st => 1 },
  { :id => 589, :type_id => 9, :full_name => 'ベッカム', :short_name => 'ベッカム', :valid_st => 1 },
  { :id => 590, :type_id => 9, :full_name => 'ベロン', :short_name => 'ベロン', :valid_st => 1 },
  { :id => 591, :type_id => 9, :full_name => 'ポール・インス', :short_name => 'P・インス', :valid_st => 1 },
  { :id => 592, :type_id => 9, :full_name => 'ポグバ', :short_name => 'ポグバ', :valid_st => 1 },
  { :id => 593, :type_id => 9, :full_name => 'ポボルスキー', :short_name => 'ポボルスキー', :valid_st => 1 },
  { :id => 594, :type_id => 9, :full_name => 'ヤヌザイ', :short_name => 'ヤヌザイ', :valid_st => 1 },
  { :id => 595, :type_id => 9, :full_name => 'リー・シャープ', :short_name => 'L・シャープ', :valid_st => 1 },
  { :id => 596, :type_id => 9, :full_name => 'ロイ・キーン', :short_name => 'ロイ・キーン', :valid_st => 1 },
  { :id => 597, :type_id => 9, :full_name => 'アーサー・アルビストン', :short_name => 'アルビストン', :valid_st => 1 },
  { :id => 598, :type_id => 9, :full_name => 'ヴィディッチ', :short_name => 'ヴィディッチ', :valid_st => 1 },
  { :id => 599, :type_id => 9, :full_name => 'ウェズ・ブラウン', :short_name => 'W・ブラウン', :valid_st => 1 },
  { :id => 600, :type_id => 9, :full_name => 'エインセ', :short_name => 'エインセ', :valid_st => 1 },
  { :id => 601, :type_id => 9, :full_name => 'エヴラ', :short_name => 'エヴラ', :valid_st => 1 },
  { :id => 602, :type_id => 9, :full_name => 'ギャリー・ネヴィル', :short_name => 'G・ネヴィル', :valid_st => 1 },
  { :id => 603, :type_id => 9, :full_name => 'ギャリー・パリスター', :short_name => 'G・パリスター', :valid_st => 1 },
  { :id => 604, :type_id => 9, :full_name => 'ケヴィン・モーラン', :short_name => 'K・モーラン', :valid_st => 1 },
  { :id => 605, :type_id => 9, :full_name => 'ジョニー・エヴァンズ', :short_name => 'J・エヴァンズ', :valid_st => 1 },
  { :id => 606, :type_id => 9, :full_name => 'ジョン・オシェイ', :short_name => 'J・オシェイ', :valid_st => 1 },
  { :id => 607, :type_id => 9, :full_name => 'スティーヴ・ブルース', :short_name => 'S・ブルース', :valid_st => 1 },
  { :id => 608, :type_id => 9, :full_name => 'スモーリング', :short_name => 'スモーリング', :valid_st => 1 },
  { :id => 609, :type_id => 9, :full_name => 'デニス・アーウィン', :short_name => 'D・アーウィン', :valid_st => 1 },
  { :id => 610, :type_id => 9, :full_name => 'ピケ', :short_name => 'ピケ', :valid_st => 1 },
  { :id => 611, :type_id => 9, :full_name => 'ファーディナンド', :short_name => 'ファーディナンド', :valid_st => 1 },
  { :id => 612, :type_id => 9, :full_name => 'ファビオ', :short_name => 'ファビオ', :valid_st => 1 },
  { :id => 613, :type_id => 9, :full_name => 'フィリップ・ネヴィル', :short_name => 'P・ネヴィル', :valid_st => 1 },
  { :id => 614, :type_id => 9, :full_name => 'フィル・ジョーンズ', :short_name => 'P・ジョーンズ', :valid_st => 1 },
  { :id => 615, :type_id => 9, :full_name => 'ポール・マグラー', :short_name => 'ポール・マグラー', :valid_st => 1 },
  { :id => 616, :type_id => 9, :full_name => 'マイク・ダックスバリー', :short_name => 'M・ダックスバリー', :valid_st => 1 },
  { :id => 617, :type_id => 9, :full_name => 'ミカエル・シルヴェストル', :short_name => 'M・シルヴェストル', :valid_st => 1 },
  { :id => 618, :type_id => 9, :full_name => 'ヤープ・スタム', :short_name => 'J・スタム', :valid_st => 1 },
  { :id => 619, :type_id => 9, :full_name => 'ヨン・シヴェベーク', :short_name => 'ヨン・シヴェベーク', :valid_st => 1 },
  { :id => 620, :type_id => 9, :full_name => 'ラファエウ', :short_name => 'ラファエウ', :valid_st => 1 },
  { :id => 621, :type_id => 9, :full_name => 'ルーク・ショー', :short_name => 'ルーク・ショー', :valid_st => 1 },
  { :id => 622, :type_id => 9, :full_name => 'ローラン・ブラン', :short_name => 'ローラン・ブラン', :valid_st => 1 },
  { :id => 623, :type_id => 9, :full_name => 'ロホ', :short_name => 'ロホ', :valid_st => 1 },
  { :id => 624, :type_id => 9, :full_name => 'ジム・レイトン', :short_name => 'ジム・レイトン', :valid_st => 1 },
  { :id => 625, :type_id => 9, :full_name => 'ティム・ハワード', :short_name => 'ティム・ハワード', :valid_st => 1 },
  { :id => 626, :type_id => 9, :full_name => 'デ・ヘア', :short_name => 'デ・ヘア', :valid_st => 1 },
  { :id => 627, :type_id => 9, :full_name => 'ピーター・シュマイケル', :short_name => 'ピーター・シュマイケル', :valid_st => 1 },
  { :id => 628, :type_id => 9, :full_name => 'ビクトル・バルデス', :short_name => 'V・バルデス', :valid_st => 1 },
  { :id => 629, :type_id => 9, :full_name => 'ファビアン・バルテズ', :short_name => 'F・バルテズ', :valid_st => 1 },
  { :id => 630, :type_id => 9, :full_name => 'ファン・デル・サール', :short_name => 'ファン・デル・サール', :valid_st => 1 },

  { :id => 631, :type_id => 10, :full_name => 'イカフライ', :short_name => 'イカフライ', :valid_st => 1 },
  { :id => 632, :type_id => 10, :full_name => '海の幸', :short_name => '海の幸', :valid_st => 1 },
  { :id => 633, :type_id => 10, :full_name => 'エビあさり', :short_name => 'エビあさり', :valid_st => 1 },
  { :id => 634, :type_id => 10, :full_name => 'エビカツ', :short_name => 'エビカツ', :valid_st => 1 },
  { :id => 635, :type_id => 10, :full_name => 'エビ煮込み', :short_name => 'エビ煮込み', :valid_st => 1 },
  { :id => 636, :type_id => 10, :full_name => 'オクラ山芋', :short_name => 'オクラ山芋', :valid_st => 1 },
  { :id => 637, :type_id => 10, :full_name => 'カニクリームコロッケ', :short_name => 'カニクリームコロッケ', :valid_st => 1 },
  { :id => 638, :type_id => 10, :full_name => 'きのこ', :short_name => 'きのこ', :valid_st => 1 },
  { :id => 639, :type_id => 10, :full_name => '牛カルビ', :short_name => '牛カルビ', :valid_st => 1 },
  { :id => 640, :type_id => 10, :full_name => 'コーン', :short_name => 'コーン', :valid_st => 1 },
  { :id => 641, :type_id => 10, :full_name => '魚フライ', :short_name => '魚フライ', :valid_st => 1 },
  { :id => 642, :type_id => 10, :full_name => 'スクランブルエッグ', :short_name => 'スクランブルエッグ', :valid_st => 1 },
  { :id => 643, :type_id => 10, :full_name => 'ソーセージ', :short_name => 'ソーセージ', :valid_st => 1 },
  { :id => 644, :type_id => 10, :full_name => 'たっぷりあさり', :short_name => 'たっぷりあさり', :valid_st => 1 },
  { :id => 645, :type_id => 10, :full_name => 'チーズ', :short_name => 'チーズ', :valid_st => 1 },
  { :id => 646, :type_id => 10, :full_name => 'チーズハンバーグ', :short_name => 'チーズハンバーグ', :valid_st => 1 },
  { :id => 647, :type_id => 10, :full_name => 'チキンカツ', :short_name => 'チキンカツ', :valid_st => 1 },
  { :id => 648, :type_id => 10, :full_name => 'チキン煮込み', :short_name => 'チキン煮込み', :valid_st => 1 },
  { :id => 649, :type_id => 10, :full_name => 'ツナ', :short_name => 'ツナ', :valid_st => 1 },
  { :id => 650, :type_id => 10, :full_name => 'トマト', :short_name => 'トマト', :valid_st => 1 },
  { :id => 651, :type_id => 10, :full_name => 'トマトアスパラ', :short_name => 'トマトアスパラ', :valid_st => 1 },
  { :id => 652, :type_id => 10, :full_name => 'とんかつ', :short_name => 'とんかつ', :valid_st => 1 },
  { :id => 653, :type_id => 10, :full_name => 'なす', :short_name => 'なす', :valid_st => 1 },
  { :id => 654, :type_id => 10, :full_name => '納豆', :short_name => '納豆', :valid_st => 1 },
  { :id => 655, :type_id => 10, :full_name => 'ハンバーグ', :short_name => 'ハンバーグ', :valid_st => 1 },
  { :id => 656, :type_id => 10, :full_name => '半熟卵つくね', :short_name => '半熟卵つくね', :valid_st => 1 },
  { :id => 657, :type_id => 10, :full_name => 'ビーフカツ', :short_name => 'ビーフカツ', :valid_st => 1 },
  { :id => 658, :type_id => 10, :full_name => 'ヒレカツ', :short_name => 'ヒレカツ', :valid_st => 1 },
  { :id => 659, :type_id => 10, :full_name => '豚しゃぶ', :short_name => '豚しゃぶ', :valid_st => 1 },
  { :id => 660, :type_id => 10, :full_name => 'フライドチキン', :short_name => 'フライドチキン', :valid_st => 1 },
  { :id => 661, :type_id => 10, :full_name => 'ほうれん草', :short_name => 'ほうれん草', :valid_st => 1 },
  { :id => 662, :type_id => 10, :full_name => 'メンチカツ', :short_name => 'メンチカツ', :valid_st => 1 },
  { :id => 663, :type_id => 10, :full_name => '野菜', :short_name => '野菜', :valid_st => 1 },
  { :id => 664, :type_id => 10, :full_name => 'ロースカツ', :short_name => 'ロースカツ', :valid_st => 1 },

  { :id => 665, :type_id => 11, :full_name => 'アリ・ダエイ', :short_name => 'アリ・ダエイ', :valid_st => 1 },
  { :id => 666, :type_id => 11, :full_name => 'エウベル', :short_name => 'エウベル', :valid_st => 1 },
  { :id => 667, :type_id => 11, :full_name => 'オリッチ', :short_name => 'オリッチ', :valid_st => 1 },
  { :id => 668, :type_id => 11, :full_name => 'クラウディオ・ピサーロ', :short_name => 'C・ピサーロ', :valid_st => 1 },
  { :id => 669, :type_id => 11, :full_name => 'クリンスマン', :short_name => 'クリンスマン', :valid_st => 1 },
  { :id => 670, :type_id => 11, :full_name => 'クローゼ', :short_name => 'クローゼ', :valid_st => 1 },
  { :id => 671, :type_id => 11, :full_name => 'ゲルト・ミュラー', :short_name => 'ゲルト・ミュラー', :valid_st => 1 },
  { :id => 672, :type_id => 11, :full_name => 'エミル・コスタディノフ', :short_name => 'コスタディノフ', :valid_st => 1 },
  { :id => 673, :type_id => 11, :full_name => 'サンタ・クルス', :short_name => 'サンタ・クルス', :valid_st => 1 },
  { :id => 674, :type_id => 11, :full_name => 'アレクサンダー・ツィックラー', :short_name => 'ツィックラー', :valid_st => 1 },
  { :id => 675, :type_id => 11, :full_name => 'ディーター・ヘーネス', :short_name => 'D・ヘーネス', :valid_st => 1 },
  { :id => 676, :type_id => 11, :full_name => 'パオロ・ゲレーロ', :short_name => 'P・ゲレーロ', :valid_st => 1 },
  { :id => 677, :type_id => 11, :full_name => 'ジャン＝ピエール・パパン', :short_name => 'パパン', :valid_st => 1 },
  { :id => 678, :type_id => 11, :full_name => 'ブライアン・ラウドルップ', :short_name => 'B・ラウドルップ', :valid_st => 1 },
  { :id => 679, :type_id => 11, :full_name => 'ポドルスキ', :short_name => 'ポドルスキ', :valid_st => 1 },
  { :id => 680, :type_id => 11, :full_name => 'マカーイ', :short_name => 'マカーイ', :valid_st => 1 },
  { :id => 681, :type_id => 11, :full_name => 'マリオ・ゴメス', :short_name => 'マリオ・ゴメス', :valid_st => 1 },
  { :id => 682, :type_id => 11, :full_name => 'マンジュキッチ', :short_name => 'マンジュキッチ', :valid_st => 1 },
  { :id => 683, :type_id => 11, :full_name => 'ミュラー', :short_name => 'ミュラー', :valid_st => 1 },
  { :id => 684, :type_id => 11, :full_name => 'カルステン・ヤンカー', :short_name => 'ヤンカー', :valid_st => 1 },
  { :id => 685, :type_id => 11, :full_name => 'ルカ・トーニ', :short_name => 'ルカ・トーニ', :valid_st => 1 },
  { :id => 686, :type_id => 11, :full_name => 'ルンメニゲ', :short_name => 'ルンメニゲ', :valid_st => 1 },
  { :id => 687, :type_id => 11, :full_name => 'レヴァンドフスキ', :short_name => 'レヴァンドフスキ', :valid_st => 1 },
  { :id => 688, :type_id => 11, :full_name => 'ローラント･ボールファルト', :short_name => 'R・ボールファルト', :valid_st => 1 },
  { :id => 689, :type_id => 11, :full_name => 'アリ・カリミ', :short_name => 'アリ・カリミ', :valid_st => 1 },
  { :id => 690, :type_id => 11, :full_name => 'ハミト・アルティントップ', :short_name => 'アルティントップ', :valid_st => 1 },
  { :id => 691, :type_id => 11, :full_name => 'アンドレアス・オットル', :short_name => 'A・オットル', :valid_st => 1 },
  { :id => 692, :type_id => 11, :full_name => 'アンドレアス・ヘルツォーク', :short_name => 'A・ヘルツォーク', :valid_st => 1 },
  { :id => 693, :type_id => 11, :full_name => 'イェンス・イェレミース', :short_name => 'イェレミース', :valid_st => 1 },
  { :id => 694, :type_id => 11, :full_name => '宇佐美貴史', :short_name => '宇佐美貴史', :valid_st => 1 },
  { :id => 695, :type_id => 11, :full_name => 'ウリ・ヘーネス', :short_name => 'ウリ・ヘーネス', :valid_st => 1 },
  { :id => 696, :type_id => 11, :full_name => 'シュテファン・エッフェンベルク', :short_name => 'エッフェンベルク', :valid_st => 1 },
  { :id => 697, :type_id => 11, :full_name => 'オラフ・トーン', :short_name => 'オラフ・トーン', :valid_st => 1 },
  { :id => 698, :type_id => 11, :full_name => 'クロース', :short_name => 'クロース', :valid_st => 1 },
  { :id => 699, :type_id => 11, :full_name => 'ゲッツェ', :short_name => 'ゲッツェ', :valid_st => 1 },
  { :id => 700, :type_id => 11, :full_name => 'ハサン・サリハミジッチ', :short_name => 'サリハミジッチ', :valid_st => 1 },
  { :id => 701, :type_id => 11, :full_name => 'シャキリ', :short_name => 'シャキリ', :valid_st => 1 },
  { :id => 702, :type_id => 11, :full_name => 'シャビ・アロンソ', :short_name => 'シャビ・アロンソ', :valid_st => 1 },
  { :id => 703, :type_id => 11, :full_name => 'ジャンルカ・ガウディーノ', :short_name => 'G・ガウディーノ', :valid_st => 1 },
  { :id => 704, :type_id => 11, :full_name => 'シュバインシュタイガー', :short_name => 'シュバインシュタイガー', :valid_st => 1 },
  { :id => 705, :type_id => 11, :full_name => 'メーメット・ショル', :short_name => 'ショル', :valid_st => 1 },
  { :id => 706, :type_id => 11, :full_name => 'セーレン・レアビー', :short_name => 'S・レアビー', :valid_st => 1 },
  { :id => 707, :type_id => 11, :full_name => 'セバスティアン・ダイスラー', :short_name => 'S・ダイスラー', :valid_st => 1 },
  { :id => 708, :type_id => 11, :full_name => 'ゼ・ロベルト', :short_name => 'ゼ・ロベルト', :valid_st => 1 },
  { :id => 709, :type_id => 11, :full_name => 'ソサ', :short_name => 'ソサ', :valid_st => 1 },
  { :id => 710, :type_id => 11, :full_name => 'ダヴィド・アラバ', :short_name => 'D・アラバ', :valid_st => 1 },
  { :id => 711, :type_id => 11, :full_name => 'ミヒャエル・タルナト', :short_name => 'タルナト', :valid_st => 1 },
  { :id => 712, :type_id => 11, :full_name => 'ディートマー・ハマン', :short_name => 'D・ハマン', :valid_st => 1 },
  { :id => 713, :type_id => 11, :full_name => 'ティアゴ・アルカンタラ', :short_name => 'T・アルカンタラ', :valid_st => 1 },
  { :id => 714, :type_id => 11, :full_name => 'ティモシュチュク', :short_name => 'ティモシュチュク', :valid_st => 1 },
  { :id => 715, :type_id => 11, :full_name => 'トーマス・シュトルンツ', :short_name => 'T・シュトルンツ', :valid_st => 1 },
  { :id => 716, :type_id => 11, :full_name => 'トルステン・フィンク', :short_name => 'T・フィンク', :valid_st => 1 },
  { :id => 717, :type_id => 11, :full_name => 'ニコ・コヴァチ', :short_name => 'ニコ・コヴァチ', :valid_st => 1 },
  { :id => 718, :type_id => 11, :full_name => 'クリスティアン・ネルリンガー', :short_name => 'ネルリンガー', :valid_st => 1 },
  { :id => 719, :type_id => 11, :full_name => 'ハーグリーヴス', :short_name => 'ハーグリーヴス', :valid_st => 1 },
  { :id => 720, :type_id => 11, :full_name => 'マリオ・バスラー', :short_name => 'バスラー', :valid_st => 1 },
  { :id => 721, :type_id => 11, :full_name => 'ハビ・マルティネス', :short_name => 'ハビ・マルティネス', :valid_st => 1 },
  { :id => 722, :type_id => 11, :full_name => 'バラック', :short_name => 'バラック', :valid_st => 1 },
  { :id => 723, :type_id => 11, :full_name => 'ファン・ボメル', :short_name => 'ファン・ボメル', :valid_st => 1 },
  { :id => 724, :type_id => 11, :full_name => 'ダニエル・プラニッチ', :short_name => 'プラニッチ', :valid_st => 1 },
  { :id => 725, :type_id => 11, :full_name => 'フリンクス', :short_name => 'フリンクス', :valid_st => 1 },
  { :id => 726, :type_id => 11, :full_name => 'ティム・ボロウスキ', :short_name => 'ボロウスキ', :valid_st => 1 },
  { :id => 727, :type_id => 11, :full_name => 'ローター・マテウス', :short_name => 'マテウス', :valid_st => 1 },
  { :id => 728, :type_id => 11, :full_name => 'リベリー', :short_name => 'リベリー', :valid_st => 1 },
  { :id => 729, :type_id => 11, :full_name => 'ルイス・グスタヴォ', :short_name => 'L・グスタヴォ', :valid_st => 1 },
  { :id => 730, :type_id => 11, :full_name => 'ロッベン', :short_name => 'ロッベン', :valid_st => 1 },
  { :id => 731, :type_id => 11, :full_name => 'クラウス・アウゲンターラー', :short_name => 'アウゲンターラー', :valid_st => 1 },
  { :id => 732, :type_id => 11, :full_name => 'ヴァレリアン・イスマエル', :short_name => 'V・イスマエル', :valid_st => 1 },
  { :id => 733, :type_id => 11, :full_name => 'オリバー･クロイツァー', :short_name => 'O･クロイツァー', :valid_st => 1 },
  { :id => 734, :type_id => 11, :full_name => 'サミュエル・クフォー', :short_name => 'クフォー', :valid_st => 1 },
  { :id => 735, :type_id => 11, :full_name => 'クリスティアン・ツィーゲ', :short_name => 'C・ツィーゲ', :valid_st => 1 },
  { :id => 736, :type_id => 11, :full_name => 'クリスティアン・レル', :short_name => 'C・レル', :valid_st => 1 },
  { :id => 737, :type_id => 11, :full_name => 'ウィリー・サニョル', :short_name => 'サニョル', :valid_st => 1 },
  { :id => 738, :type_id => 11, :full_name => 'ジェローム・ボアテング', :short_name => 'J・ボアテング', :valid_st => 1 },
  { :id => 739, :type_id => 11, :full_name => 'シュテファン・ロイター', :short_name => 'S・ロイター', :valid_st => 1 },
  { :id => 740, :type_id => 11, :full_name => 'ハンス=ゲオルク・シュバルツェンベック', :short_name => 'シュバルツェンベック', :valid_st => 1 },
  { :id => 741, :type_id => 11, :full_name => 'ジョルジーニョ', :short_name => 'ジョルジーニョ', :valid_st => 1 },
  { :id => 742, :type_id => 11, :full_name => 'ダンテ', :short_name => 'ダンテ', :valid_st => 1 },
  { :id => 743, :type_id => 11, :full_name => 'ディエゴ・コンテント', :short_name => 'D・コンテント', :valid_st => 1 },
  { :id => 744, :type_id => 11, :full_name => 'デミチェリス', :short_name => 'デミチェリス', :valid_st => 1 },
  { :id => 745, :type_id => 11, :full_name => 'トーマス・ヘルマー', :short_name => 'T・ヘルマー', :valid_st => 1 },
  { :id => 746, :type_id => 11, :full_name => 'ホルガー・バトシュトゥバー', :short_name => 'バトシュトゥバー', :valid_st => 1 },
  { :id => 747, :type_id => 11, :full_name => 'パトリック・アンデション', :short_name => 'P・アンデション', :valid_st => 1 },
  { :id => 748, :type_id => 11, :full_name => 'ファン・ブイテン', :short_name => 'ファン・ブイテン', :valid_st => 1 },
  { :id => 749, :type_id => 11, :full_name => 'ブライトナー', :short_name => 'ブライトナー', :valid_st => 1 },
  { :id => 750, :type_id => 11, :full_name => 'アンドレアス・ブレーメ', :short_name => 'ブレーメ', :valid_st => 1 },
  { :id => 751, :type_id => 11, :full_name => 'フンメルス', :short_name => 'フンメルス', :valid_st => 1 },
  { :id => 752, :type_id => 11, :full_name => 'ベッケンバウアー', :short_name => 'ベッケンバウアー', :valid_st => 1 },
  { :id => 753, :type_id => 11, :full_name => 'ベナティア', :short_name => 'ベナティア', :valid_st => 1 },
  { :id => 754, :type_id => 11, :full_name => 'マルクス・バッベル', :short_name => 'M・バッベル', :valid_st => 1 },
  { :id => 755, :type_id => 11, :full_name => 'マルセル・ヤンセン', :short_name => 'M・ヤンセン', :valid_st => 1 },
  { :id => 756, :type_id => 11, :full_name => 'ヤン・キルヒホフ', :short_name => 'ヤン・キルヒホフ', :valid_st => 1 },
  { :id => 757, :type_id => 11, :full_name => 'ユルゲン・コーラー', :short_name => 'ユルゲン・コーラー', :valid_st => 1 },
  { :id => 758, :type_id => 11, :full_name => 'ラーム', :short_name => 'ラーム', :valid_st => 1 },
  { :id => 759, :type_id => 11, :full_name => 'ラフィーニャ', :short_name => 'ラフィーニャ', :valid_st => 1 },
  { :id => 760, :type_id => 11, :full_name => 'ビセンテ・リザラズ', :short_name => 'リザラズ', :valid_st => 1 },
  { :id => 761, :type_id => 11, :full_name => 'トーマス・リンケ', :short_name => 'リンケ', :valid_st => 1 },
  { :id => 762, :type_id => 11, :full_name => 'ルシオ', :short_name => 'ルシオ', :valid_st => 1 },
  { :id => 763, :type_id => 11, :full_name => 'ロベルト・コヴァチ', :short_name => 'R・コヴァチ', :valid_st => 1 },
  { :id => 764, :type_id => 11, :full_name => 'オリバー・カーン', :short_name => 'オリバー・カーン', :valid_st => 1 },
  { :id => 765, :type_id => 11, :full_name => 'ジャン＝マリー・プファフ', :short_name => 'ジャン＝マリー・プファフ', :valid_st => 1 },
  { :id => 766, :type_id => 11, :full_name => 'ゼップ・マイヤー', :short_name => 'ゼップ・マイヤー', :valid_st => 1 },
  { :id => 767, :type_id => 11, :full_name => 'ノイアー', :short_name => 'ノイアー', :valid_st => 1 },
  { :id => 768, :type_id => 11, :full_name => 'ハンス＝イェルク・ブット', :short_name => 'ハンス＝イェルク・ブット', :valid_st => 1 },
  { :id => 769, :type_id => 11, :full_name => 'ライモント・アウマン', :short_name => 'ライモント・アウマン', :valid_st => 1 },
  { :id => 770, :type_id => 11, :full_name => 'レイナ', :short_name => 'レイナ', :valid_st => 1 },
].each do |record|
  player = Player.where(:id => record[:id]).first
  if player
    player.type_id = record[:type_id]
    player.full_name = record[:full_name]
    player.short_name = record[:short_name]
    player.valid_st = record[:valid_st]
  else
    player = Player.new(record)
  end
  player.save
end

[
  { :id => 1, :type_name => '4-4-2', :title => '4-4-2(ダイヤモンド)', :css_title => '4-4-2-a', :image_position => '{"1":{"x":"122","y":"2"},"2":{"x":"256","y":"2"},"3":{"x":"189","y":"120"},"4":{"x":"62","y":"185"},"5":{"x":"189","y":"255"},"6":{"x":"316","y":"185"},"7":{"x":"40","y":"360"},"8":{"x":"137","y":"370"},"9":{"x":"240","y":"370"},"10":{"x":"337","y":"360"},"11":{"x":"189","y":"485"}}', :text_position => '' },
  { :id => 2, :type_name => '3-4-3', :title => '3-4-3(ダイヤモンド)', :css_title => '3-4-3-a', :image_position => '{"1":{"x":"189","y":"2"},"2":{"x":"63","y":"20"},"3":{"x":"314","y":"20"},"4":{"x":"43","y":"185"},"5":{"x":"189","y":"130"},"6":{"x":"336","y":"185"},"7":{"x":"189","y":"250"},"8":{"x":"63","y":"365"},"9":{"x":"189","y":"365"},"10":{"x":"314","y":"365"},"11":{"x":"189","y":"485"}}', :text_position => '' },
  { :id => 3, :type_name => '4-2-3-1', :title => '4-2-3-1', :css_title => '4-2-3-1', :image_position => '{"1":{"x":"189","y":"2"},"2":{"x":"63","y":"130"},"3":{"x":"189","y":"130"},"4":{"x":"314","y":"130"},"5":{"x":"122","y":"250"},"6":{"x":"256","y":"250"},"7":{"x":"40","y":"360"},"8":{"x":"137","y":"370"},"9":{"x":"240","y":"370"},"10":{"x":"337","y":"360"},"11":{"x":"189","y":"485"}}', :text_position => '' },
  { :id => 4, :type_name => '4-4-2', :title => '4-4-2', :css_title => '4-4-2-b', :image_position => '{"1":{"x":"122","y":"2"},"2":{"x":"256","y":"2"},"3":{"x":"122","y":"225"},"4":{"x":"40","y":"135"},"5":{"x":"256","y":"225"},"6":{"x":"337","y":"135"},"7":{"x":"40","y":"340"},"8":{"x":"137","y":"370"},"9":{"x":"240","y":"370"},"10":{"x":"337","y":"340"},"11":{"x":"189","y":"485"}}', :text_position => '' },
  { :id => 5, :type_name => '4-3-3', :title => '4-3-3', :css_title => '4-3-3', :image_position => '{"1":{"x":"189","y":"2"},"2":{"x":"48","y":"50"},"3":{"x":"189","y":"255"},"4":{"x":"329","y":"50"},"5":{"x":"122","y":"150"},"6":{"x":"256","y":"150"},"7":{"x":"40","y":"330"},"8":{"x":"137","y":"370"},"9":{"x":"240","y":"370"},"10":{"x":"337","y":"330"},"11":{"x":"189","y":"485"}}', :text_position => '' },
].each do |record|
  formation = Formation.where(:id => record[:id]).first
  if formation
    formation.type_name = record[:type_name]
    formation.title = record[:title]
    formation.css_title = record[:css_title]
    formation.image_position = record[:image_position]
    formation.text_position = record[:text_position]
  else
    formation = Formation.new(record)
  end
  formation.save
end

[
  { :id => 1, :title => '味噌汁の具', :description => '好きな具でベストイレブンを組め', :valid_player_type_ids => '[1]', :valid_st => 1 },
  { :id => 2, :title => '職業', :description => '職業毎の特徴をいかしてベストイレブンを組め', :valid_player_type_ids => '[2]', :valid_st => 1 },
  { :id => 3, :title => 'W杯戦士', :description => 'W杯戦士でベストイレブンを組め', :valid_player_type_ids => '[3]', :valid_st => 1 },
  { :id => 4, :title => '歴代レアルマドリード', :description => '歴代選手(1996〜2015年)でベストイレブンを組め', :valid_player_type_ids => '[4]', :valid_st => 1 },
  { :id => 5, :title => 'アスリート', :description => '超人的アスリートでベストイレブンを組め', :valid_player_type_ids => '[5]', :valid_st => 1 },
  { :id => 6, :title => '歴代バルセロナ', :description => '歴代選手(1988〜2015年)でベストイレブンを組め', :valid_player_type_ids => '[6]', :valid_st => 1 },
  { :id => 7, :title => '歴代ACミラン', :description => '歴代選手(1988〜2015年)でベストイレブンを組め', :valid_player_type_ids => '[7]', :valid_st => 1 },
  { :id => 8, :title => '歴代Jリーグ', :description => '歴代受賞者(1993〜2014年)でJリーグベストイレブンを組め', :valid_player_type_ids => '[8]', :valid_st => 1 },
  { :id => 9, :title => '歴代マンチェスターU', :description => '歴代選手(1986〜2015年)でベストイレブンを組め', :valid_player_type_ids => '[9]', :valid_st => 1 },
  { :id => 10, :title => 'カレートッピング', :description => 'カレーのトッピングでベストイレブンを組め', :valid_player_type_ids => '[10]', :valid_st => 1 },
  { :id => 11, :title => '歴代バイエルンミュンヘン', :description => '歴代選手でベストイレブンを組め', :valid_player_type_ids => '[11]', :valid_st => 1 },
].each do |record|
  question = Question.where(:id => record[:id]).first
  if question
    question.title = record[:title]
    question.description = record[:description]
    question.valid_player_type_ids = record[:valid_player_type_ids]
    question.valid_st = record[:valid_st]
  else
    question = Question.new(record)
  end
  question.save
end

[
  { :id => 1, :title => '味噌汁の具' },
  { :id => 2, :title => '職業' },
  { :id => 3, :title => 'W杯戦士' },
  { :id => 4, :title => '歴代レアルマドリード' },
  { :id => 5, :title => 'アスリート' },
  { :id => 6, :title => '歴代バルセロナ' },
  { :id => 7, :title => '歴代ACミラン' },
  { :id => 8, :title => '歴代Jリーグ' },
  { :id => 9, :title => '歴代マンチェスターU' },
  { :id => 10, :title => 'カレートッピング' },
  { :id => 11, :title => '歴代バイエルンミュンヘン' },
].each do |record|
  player_type = PlayerType.where(:id => record[:id]).first
  if player_type
    player_type.title = record[:title]
  else
    player_type = PlayerType.new(record)
  end
  player_type.save
end

#[
#  { :id => 1, :valid_st => 0 },
#].each do |record|
#  maintenance = Maintenance.where(:id => record[:id]).first
#  if maintenance
#    maintenance.valid_st = record[:valid_st]
#  else
#    maintenance = Maintenance.new(record)
#  end
#  maintenance.save
#end
#
