# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).

[
  { :id => 1, :type_id => 1, :full_name => 'ナス', :short_name => 'ナス', :valid_st => 1 },
  { :id => 2, :type_id => 1, :full_name => '豆腐', :short_name => '豆腐', :valid_st => 1 },
  { :id => 3, :type_id => 1, :full_name => 'しじみ', :short_name => 'しじみ', :valid_st => 1 },
  { :id => 4, :type_id => 1, :full_name => 'ほうれん草', :short_name => 'ほうれん草', :valid_st => 1 },
  { :id => 5, :type_id => 1, :full_name => '大根', :short_name => '大根', :valid_st => 1 },
  { :id => 6, :type_id => 1, :full_name => '豚汁', :short_name => '豚汁', :valid_st => 1 },
  { :id => 7, :type_id => 1, :full_name => 'ふ', :short_name => 'ふ', :valid_st => 1 },
  { :id => 8, :type_id => 1, :full_name => 'キャベツ', :short_name => 'キャベツ', :valid_st => 1 },
  { :id => 9, :type_id => 1, :full_name => 'カボチャ', :short_name => 'カボチャ', :valid_st => 1 },
  { :id => 10, :type_id => 1, :full_name => '玉ねぎ', :short_name => '玉ねぎ', :valid_st => 1 },
  { :id => 11, :type_id => 1, :full_name => '油揚げ', :short_name => '油揚げ', :valid_st => 1 },
  { :id => 12, :type_id => 1, :full_name => '長ネギ', :short_name => '長ネギ', :valid_st => 1 },
  { :id => 13, :type_id => 1, :full_name => 'しめじ', :short_name => 'しめじ', :valid_st => 1 },
  { :id => 14, :type_id => 1, :full_name => 'えのき', :short_name => 'えのき', :valid_st => 1 },
  { :id => 15, :type_id => 1, :full_name => '白菜', :short_name => '白菜', :valid_st => 1 },
  { :id => 16, :type_id => 1, :full_name => 'カブ', :short_name => 'カブ', :valid_st => 1 },
  { :id => 17, :type_id => 1, :full_name => 'アオサ', :short_name => 'アオサ', :valid_st => 1 },
  { :id => 18, :type_id => 2, :full_name => '医師', :short_name => '医師', :valid_st => 1 },
  { :id => 19, :type_id => 2, :full_name => '板前', :short_name => '板前', :valid_st => 1 },
  { :id => 20, :type_id => 2, :full_name => 'プログラマー', :short_name => 'プログラマー', :valid_st => 1 },
  { :id => 21, :type_id => 2, :full_name => 'お笑い芸人', :short_name => 'お笑い芸人', :valid_st => 1 },
  { :id => 22, :type_id => 2, :full_name => '音楽家', :short_name => '音楽家', :valid_st => 1 },
  { :id => 23, :type_id => 2, :full_name => '看護師', :short_name => '看護師', :valid_st => 1 },
  { :id => 24, :type_id => 2, :full_name => '起業家', :short_name => '起業家', :valid_st => 1 },
  { :id => 25, :type_id => 2, :full_name => '気象予報士', :short_name => '気象予報士', :valid_st => 1 },
  { :id => 26, :type_id => 2, :full_name => 'キックボクサー', :short_name => 'キックボクサー', :valid_st => 1 },
  { :id => 27, :type_id => 2, :full_name => '警備員', :short_name => '警備員', :valid_st => 1 },
  { :id => 28, :type_id => 2, :full_name => 'ダンサー', :short_name => 'ダンサー', :valid_st => 1 },
  { :id => 29, :type_id => 2, :full_name => '配管工', :short_name => '配管工', :valid_st => 1 },
  { :id => 30, :type_id => 2, :full_name => '農家', :short_name => '農家', :valid_st => 1 },
  { :id => 31, :type_id => 2, :full_name => '登山家', :short_name => '登山家', :valid_st => 1 },
  { :id => 32, :type_id => 2, :full_name => 'テニス選手', :short_name => 'テニス選手', :valid_st => 1 },
  { :id => 33, :type_id => 2, :full_name => '力士', :short_name => '力士', :valid_st => 1 },
  { :id => 34, :type_id => 2, :full_name => 'ラグビー選手', :short_name => 'ラグビー選手', :valid_st => 1 },
  { :id => 35, :type_id => 2, :full_name => 'レスキュー隊員', :short_name => 'レスキュー隊員', :valid_st => 1 },
  { :id => 36, :type_id => 2, :full_name => 'レーサー', :short_name => 'レーサー', :valid_st => 1 },
  { :id => 37, :type_id => 2, :full_name => 'バスケットボール選手', :short_name => 'バスケットボール選手', :valid_st => 1 },
  { :id => 38, :type_id => 2, :full_name => '占い師', :short_name => '占い師', :valid_st => 1 },
  { :id => 39, :type_id => 2, :full_name => '宇宙飛行士', :short_name => '宇宙飛行士', :valid_st => 1 },
  { :id => 40, :type_id => 2, :full_name => '警察官', :short_name => '警察官', :valid_st => 1 },
  { :id => 41, :type_id => 2, :full_name => 'プロ野球選手', :short_name => 'プロ野球選手', :valid_st => 1 },
  { :id => 42, :type_id => 2, :full_name => '柔道家', :short_name => '柔道家', :valid_st => 1 },
  { :id => 43, :type_id => 2, :full_name => 'プロボクサー', :short_name => 'プロボクサー', :valid_st => 1 },
  { :id => 44, :type_id => 2, :full_name => 'プロゴルファー', :short_name => 'プロゴルファー', :valid_st => 1 },
  { :id => 45, :type_id => 2, :full_name => '卓球選手', :short_name => '卓球選手', :valid_st => 1 },
  { :id => 46, :type_id => 2, :full_name => 'プロレスラー', :short_name => 'プロレスラー', :valid_st => 1 },
  { :id => 47, :type_id => 2, :full_name => '空手家', :short_name => '空手家', :valid_st => 1 },
  { :id => 48, :type_id => 1, :full_name => 'なめこ', :short_name => 'なめこ', :valid_st => 1 },
  { :id => 49, :type_id => 1, :full_name => 'わかめ', :short_name => 'わかめ', :valid_st => 1 },
  { :id => 50, :type_id => 3, :full_name => '川口能活', :short_name => '川口能活', :valid_st => 1 },
  { :id => 51, :type_id => 3, :full_name => '川島永嗣', :short_name => '川島永嗣', :valid_st => 1 },
  { :id => 52, :type_id => 3, :full_name => '楢崎正剛', :short_name => '楢崎正剛', :valid_st => 1 },
  { :id => 53, :type_id => 3, :full_name => '秋田豊', :short_name => '秋田豊', :valid_st => 1 },
  { :id => 54, :type_id => 3, :full_name => '伊野波雅彦', :short_name => '伊野波雅彦', :valid_st => 1 },
  { :id => 55, :type_id => 3, :full_name => '井原正巳', :short_name => '井原正巳', :valid_st => 1 },
  { :id => 56, :type_id => 3, :full_name => '内田篤人', :short_name => '内田篤人', :valid_st => 1 },
  { :id => 57, :type_id => 3, :full_name => '小村徳男', :short_name => '小村徳男', :valid_st => 1 },
  { :id => 58, :type_id => 3, :full_name => '加地亮', :short_name => '加地亮', :valid_st => 1 },
  { :id => 59, :type_id => 3, :full_name => '駒野友一', :short_name => '駒野友一', :valid_st => 1 },
  { :id => 60, :type_id => 3, :full_name => '今野泰幸', :short_name => '今野泰幸', :valid_st => 1 },
  { :id => 61, :type_id => 3, :full_name => '三都主アレサンドロ', :short_name => '三都主', :valid_st => 1 },
  { :id => 62, :type_id => 3, :full_name => '相馬直樹', :short_name => '相馬直樹', :valid_st => 1 },
  { :id => 63, :type_id => 3, :full_name => '田中マルクス闘莉王', :short_name => '闘莉王', :valid_st => 1 },
  { :id => 64, :type_id => 3, :full_name => '坪井慶介', :short_name => '坪井慶介', :valid_st => 1 },
  { :id => 65, :type_id => 3, :full_name => '中澤佑二', :short_name => '中澤佑二', :valid_st => 1 },
  { :id => 66, :type_id => 3, :full_name => '中田浩二', :short_name => '中田浩二', :valid_st => 1 },
  { :id => 67, :type_id => 3, :full_name => '長友佑都', :short_name => '長友佑都', :valid_st => 1 },
  { :id => 68, :type_id => 3, :full_name => '名良橋晃', :short_name => '名良橋晃', :valid_st => 1 },
  { :id => 69, :type_id => 3, :full_name => '松田直樹', :short_name => '松田直樹', :valid_st => 1 },
  { :id => 70, :type_id => 3, :full_name => '宮本恒靖', :short_name => '宮本恒靖', :valid_st => 1 },
  { :id => 71, :type_id => 3, :full_name => '森岡隆三', :short_name => '森岡隆三', :valid_st => 1 },
  { :id => 72, :type_id => 3, :full_name => '吉田麻也', :short_name => '吉田麻也', :valid_st => 1 },
  { :id => 73, :type_id => 3, :full_name => '阿部勇樹', :short_name => '阿部勇樹', :valid_st => 1 },
  { :id => 74, :type_id => 3, :full_name => '伊東輝悦', :short_name => '伊東輝悦', :valid_st => 1 },
  { :id => 75, :type_id => 3, :full_name => '稲本潤一', :short_name => '稲本潤一', :valid_st => 1 },
  { :id => 76, :type_id => 3, :full_name => '遠藤保仁', :short_name => '遠藤保仁', :valid_st => 1 },
  { :id => 77, :type_id => 3, :full_name => '小笠原満男', :short_name => '小笠原満男', :valid_st => 1 },
  { :id => 78, :type_id => 3, :full_name => '小野伸二', :short_name => '小野伸二', :valid_st => 1 },
  { :id => 79, :type_id => 3, :full_name => '香川真司', :short_name => '香川真司', :valid_st => 1 },
  { :id => 80, :type_id => 3, :full_name => '清武弘嗣', :short_name => '清武弘嗣', :valid_st => 1 },
  { :id => 81, :type_id => 3, :full_name => '戸田和幸', :short_name => '戸田和幸', :valid_st => 1 },
  { :id => 82, :type_id => 3, :full_name => '中田英寿', :short_name => '中田英寿', :valid_st => 1 },
  { :id => 83, :type_id => 3, :full_name => '中村憲剛', :short_name => '中村憲剛', :valid_st => 1 },
  { :id => 84, :type_id => 3, :full_name => '中村俊輔', :short_name => '中村俊輔', :valid_st => 1 },
  { :id => 85, :type_id => 3, :full_name => '名波浩', :short_name => '名波浩', :valid_st => 1 },
  { :id => 86, :type_id => 3, :full_name => '長谷部誠', :short_name => '長谷部誠', :valid_st => 1 },
  { :id => 87, :type_id => 3, :full_name => '服部年宏', :short_name => '服部年宏', :valid_st => 1 },
  { :id => 88, :type_id => 3, :full_name => '福西崇史', :short_name => '福西崇史', :valid_st => 1 },
  { :id => 89, :type_id => 3, :full_name => '本田圭佑', :short_name => '本田圭佑', :valid_st => 1 },
  { :id => 90, :type_id => 3, :full_name => '松井大輔', :short_name => '松井大輔', :valid_st => 1 },
  { :id => 91, :type_id => 3, :full_name => '明神智和', :short_name => '明神智和', :valid_st => 1 },
  { :id => 92, :type_id => 3, :full_name => '山口素弘', :short_name => '山口素弘', :valid_st => 1 },

  { :id => 93, :type_id => 3, :full_name => '大久保嘉人', :short_name => '大久保嘉人', :valid_st => 1 },
  { :id => 94, :type_id => 3, :full_name => '大黒将志', :short_name => '大黒将志', :valid_st => 1 },
  { :id => 95, :type_id => 3, :full_name => '岡崎慎司', :short_name => '岡崎慎司', :valid_st => 1 },
  { :id => 96, :type_id => 3, :full_name => '岡野雅行', :short_name => '岡野雅行', :valid_st => 1 },
  { :id => 97, :type_id => 3, :full_name => '城彰二', :short_name => '城彰二', :valid_st => 1 },
  { :id => 98, :type_id => 3, :full_name => '鈴木隆行', :short_name => '鈴木隆行', :valid_st => 1 },
  { :id => 99, :type_id => 3, :full_name => '高原直泰', :short_name => '高原直泰', :valid_st => 1 },
  { :id => 100, :type_id => 3, :full_name => '玉田圭司', :short_name => '玉田圭司', :valid_st => 1 },
  { :id => 101, :type_id => 3, :full_name => '中山雅史', :short_name => '中山雅史', :valid_st => 1 },
  { :id => 102, :type_id => 3, :full_name => '西澤明訓', :short_name => '西澤明訓', :valid_st => 1 },
  { :id => 103, :type_id => 3, :full_name => '巻誠一郎', :short_name => '巻誠一郎', :valid_st => 1 },
  { :id => 104, :type_id => 3, :full_name => '森島寛晃', :short_name => '森島寛晃', :valid_st => 1 },
  { :id => 105, :type_id => 3, :full_name => '柳沢敦', :short_name => '柳沢敦', :valid_st => 1 },
  { :id => 106, :type_id => 3, :full_name => '呂比須ワグナー', :short_name => '呂比須', :valid_st => 1 },
  { :id => 107, :type_id => 1, :full_name => 'もやし', :short_name => 'もやし', :valid_st => 1 },
  { :id => 108, :type_id => 1, :full_name => 'ひじき', :short_name => 'ひじき', :valid_st => 1 },
  { :id => 109, :type_id => 1, :full_name => 'たけのこ', :short_name => 'たけのこ', :valid_st => 1 },
  { :id => 110, :type_id => 1, :full_name => 'みょうが', :short_name => 'みょうが', :valid_st => 1 },
  { :id => 111, :type_id => 1, :full_name => 'れんこん', :short_name => 'れんこん', :valid_st => 1 },
  { :id => 112, :type_id => 1, :full_name => 'とろろ昆布', :short_name => 'とろろ昆布', :valid_st => 1 },
  { :id => 113, :type_id => 1, :full_name => 'ちくわ', :short_name => 'ちくわ', :valid_st => 1 },
  { :id => 114, :type_id => 1, :full_name => 'あら汁', :short_name => 'あら汁', :valid_st => 1 },
  { :id => 115, :type_id => 1, :full_name => 'じゃがいも', :short_name => 'じゃがいも', :valid_st => 1 },
  { :id => 116, :type_id => 4, :full_name => 'イルクナー', :short_name => 'イルクナー', :valid_st => 1 },
  { :id => 117, :type_id => 4, :full_name => 'カシージャス', :short_name => 'カシージャス', :valid_st => 1 },
  { :id => 118, :type_id => 4, :full_name => 'ディエゴ・ロペス', :short_name => 'D・ロペス', :valid_st => 1 },
  { :id => 119, :type_id => 4, :full_name => 'ナバス', :short_name => 'ナバス', :valid_st => 1 },
  { :id => 120, :type_id => 4, :full_name => 'アルビオル', :short_name => 'アルビオル', :valid_st => 1 },
  { :id => 121, :type_id => 4, :full_name => 'アルベロア', :short_name => 'アルベロア', :valid_st => 1 },
  { :id => 122, :type_id => 4, :full_name => 'イバン・カンポ', :short_name => 'I・カンポ', :valid_st => 1 },
  { :id => 123, :type_id => 4, :full_name => 'イエロ', :short_name => 'イエロ', :valid_st => 1 },
  { :id => 124, :type_id => 4, :full_name => 'ヴァラン', :short_name => 'ヴァラン', :valid_st => 1 },
  { :id => 125, :type_id => 4, :full_name => 'エインセ', :short_name => 'エインセ', :valid_st => 1 },
  { :id => 126, :type_id => 4, :full_name => 'エルゲラ', :short_name => 'エルゲラ', :valid_st => 1 },
  { :id => 127, :type_id => 4, :full_name => 'カルバハル', :short_name => 'カルバハル', :valid_st => 1 },
  { :id => 128, :type_id => 4, :full_name => 'カンナバーロ', :short_name => 'カンナバーロ', :valid_st => 1 },
  { :id => 129, :type_id => 4, :full_name => 'コエントラン', :short_name => 'コエントラン', :valid_st => 1 },
  { :id => 130, :type_id => 4, :full_name => 'サルガド', :short_name => 'サルガド', :valid_st => 1 },
  { :id => 131, :type_id => 4, :full_name => 'セルヒオ・ラモス', :short_name => 'S・ラモス', :valid_st => 1 },
  { :id => 132, :type_id => 4, :full_name => 'パボン', :short_name => 'パボン', :valid_st => 1 },
  { :id => 133, :type_id => 4, :full_name => 'ペペ', :short_name => 'ペペ', :valid_st => 1 },
  { :id => 134, :type_id => 4, :full_name => 'マルセロ', :short_name => 'マルセロ', :valid_st => 1 },
  { :id => 135, :type_id => 4, :full_name => 'ラウール・ブラボ', :short_name => 'R・ブラボ', :valid_st => 1 },
  { :id => 136, :type_id => 4, :full_name => 'リカルド・カルヴァーリョ', :short_name => 'R・カルヴァーリョ', :valid_st => 1 },
  { :id => 137, :type_id => 4, :full_name => 'ロベルト・カルロス', :short_name => 'R・カルロス', :valid_st => 1 },
  { :id => 138, :type_id => 4, :full_name => 'イスコ', :short_name => 'イスコ', :valid_st => 1 },
  { :id => 139, :type_id => 4, :full_name => 'エジル', :short_name => 'エジル', :valid_st => 1 },
  { :id => 140, :type_id => 4, :full_name => 'カカ', :short_name => 'カカ', :valid_st => 1 },
  { :id => 141, :type_id => 4, :full_name => 'ガゴ', :short_name => 'ガゴ', :valid_st => 1 },
  { :id => 142, :type_id => 4, :full_name => 'カンビアッソ', :short_name => 'カンビアッソ', :valid_st => 1 },
  { :id => 143, :type_id => 4, :full_name => 'グティ', :short_name => 'グティ', :valid_st => 1 },
  { :id => 144, :type_id => 4, :full_name => 'グラネロ', :short_name => 'グラネロ', :valid_st => 1 },
  { :id => 145, :type_id => 4, :full_name => 'クロース', :short_name => 'クロース', :valid_st => 1 },
  { :id => 146, :type_id => 4, :full_name => 'ケディラ', :short_name => 'ケディラ', :valid_st => 1 },
  { :id => 147, :type_id => 4, :full_name => 'ジダン', :short_name => 'ジダン', :valid_st => 1 },
  { :id => 148, :type_id => 4, :full_name => 'シャビ・アロンソ', :short_name => 'X・アロンソ', :valid_st => 1 },
  { :id => 149, :type_id => 4, :full_name => 'スナイデル', :short_name => 'スナイデル', :valid_st => 1 },
  { :id => 150, :type_id => 4, :full_name => 'セードルフ', :short_name => 'セードルフ', :valid_st => 1 },
  { :id => 151, :type_id => 4, :full_name => 'ソラーリ', :short_name => 'ソラーリ', :valid_st => 1 },
  { :id => 152, :type_id => 4, :full_name => 'ディ・マリア', :short_name => 'ディ・マリア', :valid_st => 1 },
  { :id => 153, :type_id => 4, :full_name => 'ハメス・ロドリゲス', :short_name => 'J・ロドリゲス', :valid_st => 1 },
  { :id => 154, :type_id => 4, :full_name => 'ファン・デル・ファールト', :short_name => 'V・D・ファールト', :valid_st => 1 },
  { :id => 155, :type_id => 4, :full_name => 'フィーゴ', :short_name => 'フィーゴ', :valid_st => 1 },
  { :id => 156, :type_id => 4, :full_name => 'ベッカム', :short_name => 'ベッカム', :valid_st => 1 },
  { :id => 157, :type_id => 4, :full_name => 'マアマドゥ・ディアラ', :short_name => 'M・ディアラ', :valid_st => 1 },
  { :id => 158, :type_id => 4, :full_name => 'マケレレ', :short_name => 'マケレレ', :valid_st => 1 },
  { :id => 159, :type_id => 4, :full_name => 'モドリッチ', :short_name => 'モドリッチ', :valid_st => 1 },
  { :id => 160, :type_id => 4, :full_name => 'ラウドルップ', :short_name => 'ラウドルップ', :valid_st => 1 },
  { :id => 161, :type_id => 4, :full_name => 'ラサナ・ディアラ', :short_name => 'L・ディアラ', :valid_st => 1 },
  { :id => 162, :type_id => 4, :full_name => 'ルイス・エンリケ', :short_name => 'L・エンリケ', :valid_st => 1 },
  { :id => 163, :type_id => 4, :full_name => 'レドンド', :short_name => 'レドンド', :valid_st => 1 },
  { :id => 164, :type_id => 4, :full_name => 'イグアイン', :short_name => 'イグアイン', :valid_st => 1 },
  { :id => 165, :type_id => 4, :full_name => 'エルナンデス', :short_name => 'エルナンデス', :valid_st => 1 },
  { :id => 166, :type_id => 4, :full_name => 'オーウェン', :short_name => 'オーウェン', :valid_st => 1 },
  { :id => 167, :type_id => 4, :full_name => 'クリスティアーノ・ロナウド', :short_name => 'C・ロナウド', :valid_st => 1 },
  { :id => 168, :type_id => 4, :full_name => 'シューケル', :short_name => 'シューケル', :valid_st => 1 },
  { :id => 169, :type_id => 4, :full_name => 'ファン・ニステルローイ', :short_name => 'V・ニステルローイ', :valid_st => 1 },
  { :id => 170, :type_id => 4, :full_name => 'ベイル', :short_name => 'ベイル', :valid_st => 1 },
  { :id => 171, :type_id => 4, :full_name => 'ベンゼマ', :short_name => 'ベンゼマ', :valid_st => 1 },
  { :id => 172, :type_id => 4, :full_name => 'ミヤトヴィッチ', :short_name => 'ミヤトヴィッチ', :valid_st => 1 },
  { :id => 173, :type_id => 4, :full_name => 'モリエンテス', :short_name => 'モリエンテス', :valid_st => 1 },
  { :id => 174, :type_id => 4, :full_name => 'ラウール', :short_name => 'ラウール', :valid_st => 1 },
  { :id => 175, :type_id => 4, :full_name => 'ロッベン', :short_name => 'ロッベン', :valid_st => 1 },
  { :id => 176, :type_id => 4, :full_name => 'ロナウド', :short_name => 'ロナウド', :valid_st => 1 },
  { :id => 177, :type_id => 4, :full_name => 'ロビーニョ', :short_name => 'ロビーニョ', :valid_st => 1 },
  { :id => 178, :type_id => 5, :full_name => '朝青龍', :short_name => '朝青龍', :valid_st => 1 },
  { :id => 179, :type_id => 5, :full_name => '朝原宣治', :short_name => '朝原宣治', :valid_st => 1 },
  { :id => 180, :type_id => 5, :full_name => 'アントニオ猪木', :short_name => 'A猪木', :valid_st => 1 },
  { :id => 181, :type_id => 5, :full_name => '五十嵐圭', :short_name => '五十嵐圭', :valid_st => 1 },
  { :id => 182, :type_id => 5, :full_name => '池谷直樹', :short_name => '池谷直樹', :valid_st => 1 },
  { :id => 183, :type_id => 5, :full_name => '石川遼', :short_name => '石川遼', :valid_st => 1 },
  { :id => 184, :type_id => 5, :full_name => 'イチロー', :short_name => 'イチロー', :valid_st => 1 },
  { :id => 185, :type_id => 5, :full_name => '内村航平', :short_name => '内村航平', :valid_st => 1 },
  { :id => 186, :type_id => 5, :full_name => '太田雄貴', :short_name => '太田雄貴', :valid_st => 1 },
  { :id => 187, :type_id => 5, :full_name => '大谷翔平', :short_name => '大谷翔平', :valid_st => 1 },
  { :id => 188, :type_id => 5, :full_name => '大畑大介', :short_name => '大畑大介', :valid_st => 1 },
  { :id => 189, :type_id => 5, :full_name => '大山倍達', :short_name => '大山倍達', :valid_st => 1 },
  { :id => 190, :type_id => 5, :full_name => '葛西紀明', :short_name => '葛西紀明', :valid_st => 1 },
  { :id => 191, :type_id => 5, :full_name => '嘉納治五郎', :short_name => '嘉納治五郎', :valid_st => 1 },
  { :id => 192, :type_id => 5, :full_name => '亀田興毅', :short_name => '亀田興毅', :valid_st => 1 },
  { :id => 193, :type_id => 5, :full_name => '亀田大毅', :short_name => '亀田大毅', :valid_st => 1 },
  { :id => 194, :type_id => 5, :full_name => '亀田和毅', :short_name => '亀田和毅', :valid_st => 1 },
  { :id => 195, :type_id => 5, :full_name => '川合俊一', :short_name => '川合俊一', :valid_st => 1 },
  { :id => 196, :type_id => 5, :full_name => '木下典明', :short_name => '木下典明', :valid_st => 1 },
  { :id => 197, :type_id => 5, :full_name => '桐生祥秀', :short_name => '桐生祥秀', :valid_st => 1 },
  { :id => 198, :type_id => 5, :full_name => '清水宏保', :short_name => '清水宏保', :valid_st => 1 },
  { :id => 199, :type_id => 5, :full_name => 'ジャイアント馬場', :short_name => 'G馬場', :valid_st => 1 },
  { :id => 200, :type_id => 5, :full_name => '照英', :short_name => '照英', :valid_st => 1 },
  { :id => 201, :type_id => 5, :full_name => '白井健三', :short_name => '白井健三', :valid_st => 1 },
  { :id => 202, :type_id => 5, :full_name => '瀬戸大也', :short_name => '瀬戸大也', :valid_st => 1 },
  { :id => 203, :type_id => 5, :full_name => '宗茂', :short_name => '宗茂', :valid_st => 1 },
  { :id => 204, :type_id => 5, :full_name => '宗猛', :short_name => '宗猛', :valid_st => 1 },
  { :id => 205, :type_id => 5, :full_name => '高橋大輔', :short_name => '高橋大輔', :valid_st => 1 },
  { :id => 206, :type_id => 5, :full_name => '武豊', :short_name => '武豊', :valid_st => 1 },
  { :id => 207, :type_id => 5, :full_name => '武井壮', :short_name => '武井壮', :valid_st => 1 },
  { :id => 208, :type_id => 5, :full_name => '田中将大', :short_name => '田中将大', :valid_st => 1 },
  { :id => 209, :type_id => 5, :full_name => '谷口浩美', :short_name => '谷口浩美', :valid_st => 1 },
  { :id => 210, :type_id => 5, :full_name => '田臥勇太', :short_name => '田臥勇太', :valid_st => 1 },
  { :id => 211, :type_id => 5, :full_name => 'ダルビッシュ有', :short_name => 'ダルビッシュ', :valid_st => 1 },
  { :id => 212, :type_id => 5, :full_name => '中田大輔', :short_name => '中田大輔', :valid_st => 1 },
  { :id => 213, :type_id => 5, :full_name => '中野浩一', :short_name => '中野浩一', :valid_st => 1 },
  { :id => 214, :type_id => 5, :full_name => '錦織圭', :short_name => '錦織圭', :valid_st => 1 },
  { :id => 215, :type_id => 5, :full_name => '野村忠宏', :short_name => '野村忠宏', :valid_st => 1 },
  { :id => 216, :type_id => 5, :full_name => '萩野公介', :short_name => '萩野公介', :valid_st => 1 },
  { :id => 217, :type_id => 5, :full_name => '白鵬', :short_name => '白鵬', :valid_st => 1 },
  { :id => 218, :type_id => 5, :full_name => '羽生結弦', :short_name => '羽生結弦', :valid_st => 1 },
  { :id => 219, :type_id => 5, :full_name => '魔裟斗', :short_name => '魔裟斗', :valid_st => 1 },
  { :id => 220, :type_id => 5, :full_name => '松岡修造', :short_name => '松岡修造', :valid_st => 1 },
  { :id => 221, :type_id => 5, :full_name => '松山英樹', :short_name => '松山英樹', :valid_st => 1 },
  { :id => 222, :type_id => 5, :full_name => '水谷隼', :short_name => '水谷隼', :valid_st => 1 },
  { :id => 223, :type_id => 5, :full_name => '宮崎大輔', :short_name => '宮崎大輔', :valid_st => 1 },
  { :id => 224, :type_id => 5, :full_name => '村上幸史', :short_name => '村上幸史', :valid_st => 1 },
  { :id => 225, :type_id => 5, :full_name => '室伏広治', :short_name => '室伏広治', :valid_st => 1 },
  { :id => 226, :type_id => 5, :full_name => '山下泰裕', :short_name => '山下泰裕', :valid_st => 1 },
  { :id => 227, :type_id => 5, :full_name => '山田勝己', :short_name => '山田勝己', :valid_st => 1 },
  { :id => 228, :type_id => 5, :full_name => 'ワッキー', :short_name => 'ワッキー', :valid_st => 1 },

  { :id => 229, :type_id => 6, :full_name => 'シュテーゲン', :short_name => 'シュテーゲン', :valid_st => 1 },
  { :id => 230, :type_id => 6, :full_name => 'スビサレッタ', :short_name => 'スビサレッタ', :valid_st => 1 },
  { :id => 231, :type_id => 6, :full_name => 'バロッソ', :short_name => 'バロッソ', :valid_st => 1 },
  { :id => 232, :type_id => 6, :full_name => 'ビクトール・バイーア', :short_name => 'V・バイーア', :valid_st => 1 },
  { :id => 233, :type_id => 6, :full_name => 'ビクトール・バルデス', :short_name => 'V・バルデス', :valid_st => 1 },
  { :id => 234, :type_id => 6, :full_name => 'ブラボ', :short_name => 'ブラボ', :valid_st => 1 },
  { :id => 235, :type_id => 6, :full_name => 'ヘスプ', :short_name => 'ヘスプ', :valid_st => 1 },
  { :id => 236, :type_id => 6, :full_name => 'アドリアーノ・コレイア', :short_name => 'A・コレイア', :valid_st => 1 },
  { :id => 237, :type_id => 6, :full_name => 'アビダル', :short_name => 'アビダル', :valid_st => 1 },
  { :id => 238, :type_id => 6, :full_name => 'アベラルド', :short_name => 'アベラルド', :valid_st => 1 },
  { :id => 239, :type_id => 6, :full_name => 'ラモン・アレサンコ', :short_name => 'アレサンコ', :valid_st => 1 },
  { :id => 240, :type_id => 6, :full_name => 'オレゲール・プレサス', :short_name => 'オレゲール', :valid_st => 1 },
  { :id => 241, :type_id => 6, :full_name => 'ガブリエル・ミリート', :short_name => 'G・ミリート', :valid_st => 1 },
  { :id => 242, :type_id => 6, :full_name => 'ロナルド・クーマン', :short_name => 'クーマン', :valid_st => 1 },
  { :id => 243, :type_id => 6, :full_name => 'ザンブロッタ', :short_name => 'ザンブロッタ', :valid_st => 1 },
  { :id => 244, :type_id => 6, :full_name => 'シウヴィーニョ', :short_name => 'シウヴィーニョ', :valid_st => 1 },
  { :id => 245, :type_id => 6, :full_name => 'ファン・ブロンクホルスト', :short_name => 'ジオ', :valid_st => 1 },
  { :id => 246, :type_id => 6, :full_name => 'ジョルディ・アルバ', :short_name => 'J・アルバ', :valid_st => 1 },
  { :id => 247, :type_id => 6, :full_name => 'セルジ・バルファン', :short_name => 'S・バルファン', :valid_st => 1 },
  { :id => 248, :type_id => 6, :full_name => 'ダニエウ・アウベス', :short_name => 'D・アウベス', :valid_st => 1 },
  { :id => 249, :type_id => 6, :full_name => 'フランク・デ・ブール', :short_name => 'デ・ブール', :valid_st => 1 },
  { :id => 250, :type_id => 6, :full_name => 'テュラム', :short_name => 'テュラム', :valid_st => 1 },
  { :id => 251, :type_id => 6, :full_name => 'ミゲル・アンヘル・ナダル', :short_name => 'ナダル', :valid_st => 1 },
  { :id => 252, :type_id => 6, :full_name => 'ナンド', :short_name => 'ナンド', :valid_st => 1 },
  { :id => 253, :type_id => 6, :full_name => 'ピケ', :short_name => 'ピケ', :valid_st => 1 },
  { :id => 254, :type_id => 6, :full_name => 'フェルメーレン', :short_name => 'フェルメーレン', :valid_st => 1 },
  { :id => 255, :type_id => 6, :full_name => 'アルベルト・フェレール', :short_name => 'フェレール', :valid_st => 1 },
  { :id => 256, :type_id => 6, :full_name => 'プジョル', :short_name => 'プジョル', :valid_st => 1 },
  { :id => 257, :type_id => 6, :full_name => 'ジュリアーノ・ベレッチ', :short_name => 'ベレッチ', :valid_st => 1 },
  { :id => 258, :type_id => 6, :full_name => 'ゲオルゲ・ポペスク', :short_name => 'ポペスク', :valid_st => 1 },
  { :id => 259, :type_id => 6, :full_name => 'マクスウェル', :short_name => 'マクスウェル', :valid_st => 1 },
  { :id => 260, :type_id => 6, :full_name => 'マスチェラーノ', :short_name => 'マスチェラーノ', :valid_st => 1 },
  { :id => 261, :type_id => 6, :full_name => 'マテュー', :short_name => 'マテュー', :valid_st => 1 },
  { :id => 262, :type_id => 6, :full_name => 'ラファエル・マルケス', :short_name => 'マルケス', :valid_st => 1 },
  { :id => 263, :type_id => 6, :full_name => 'ミゲリ', :short_name => 'ミゲリ', :valid_st => 1 },
  { :id => 264, :type_id => 6, :full_name => 'アモール', :short_name => 'アモール', :valid_st => 1 },
  { :id => 265, :type_id => 6, :full_name => 'イニエスタ', :short_name => 'イニエスタ', :valid_st => 1 },
  { :id => 266, :type_id => 6, :full_name => 'エウセビオ', :short_name => 'エウセビオ', :valid_st => 1 },
  { :id => 267, :type_id => 6, :full_name => 'エジミウソン', :short_name => 'エジミウソン', :valid_st => 1 },
  { :id => 268, :type_id => 6, :full_name => 'ガブリ', :short_name => 'ガブリ', :valid_st => 1 },
  { :id => 269, :type_id => 6, :full_name => 'グアルディオラ', :short_name => 'グアルディオラ', :valid_st => 1 },
  { :id => 270, :type_id => 6, :full_name => 'ゴイコエチェア', :short_name => 'ゴイコエチェア', :valid_st => 1 },
  { :id => 271, :type_id => 6, :full_name => 'コクー', :short_name => 'コクー', :valid_st => 1 },
  { :id => 272, :type_id => 6, :full_name => 'ジェラール・ロペス', :short_name => 'G・ロペス', :valid_st => 1 },
  { :id => 273, :type_id => 6, :full_name => 'ジオヴァンニ', :short_name => 'ジオヴァンニ', :valid_st => 1 },
  { :id => 274, :type_id => 6, :full_name => 'シャビ', :short_name => 'シャビ', :valid_st => 1 },
  { :id => 275, :type_id => 6, :full_name => 'ベルント・シュスター', :short_name => 'シュスター', :valid_st => 1 },
  { :id => 276, :type_id => 6, :full_name => 'セイドゥ・ケイタ', :short_name => 'S・ケイタ', :valid_st => 1 },
  { :id => 277, :type_id => 6, :full_name => 'セスク', :short_name => 'セスク', :valid_st => 1 },
  { :id => 278, :type_id => 6, :full_name => 'アルベルト・セラーデス', :short_name => 'セラーデス', :valid_st => 1 },
  { :id => 279, :type_id => 6, :full_name => 'ダーヴィッツ', :short_name => 'ダーヴィッツ', :valid_st => 1 },
  { :id => 280, :type_id => 6, :full_name => 'チアゴ・モッタ', :short_name => 'T・モッタ', :valid_st => 1 },
  { :id => 281, :type_id => 6, :full_name => 'デコ', :short_name => 'デコ', :valid_st => 1 },
  { :id => 282, :type_id => 6, :full_name => 'デ・ラ・ペーニャ', :short_name => 'デラペーニャ', :valid_st => 1 },
  { :id => 283, :type_id => 6, :full_name => 'バケーロ', :short_name => 'バケーロ', :valid_st => 1 },
  { :id => 284, :type_id => 6, :full_name => 'ゲオルゲ・ハジ', :short_name => 'ハジ', :valid_st => 1 },
  { :id => 285, :type_id => 6, :full_name => 'ブスケツ', :short_name => 'ブスケツ', :valid_st => 1 },
  { :id => 286, :type_id => 6, :full_name => 'プロシネチキ', :short_name => 'プロシネチキ', :valid_st => 1 },
  { :id => 287, :type_id => 6, :full_name => 'ベギリスタイン', :short_name => 'ベギリスタイン', :valid_st => 1 },
  { :id => 288, :type_id => 6, :full_name => 'ヤヤ・トゥーレ', :short_name => 'ヤヤ・トゥーレ', :valid_st => 1 },
  { :id => 289, :type_id => 6, :full_name => 'ラキティッチ', :short_name => 'ラキティッチ', :valid_st => 1 },
  { :id => 290, :type_id => 6, :full_name => 'リバウド', :short_name => 'リバウド', :valid_st => 1 },
  { :id => 291, :type_id => 6, :full_name => 'ルイス・エンリケ', :short_name => 'L・エンリケ', :valid_st => 1 },
  { :id => 292, :type_id => 6, :full_name => 'アレクシス・サンチェス', :short_name => 'A・サンチェス', :valid_st => 1 },
  { :id => 293, :type_id => 6, :full_name => 'アンリ', :short_name => 'アンリ', :valid_st => 1 },
  { :id => 294, :type_id => 6, :full_name => 'イブラヒモビッチ', :short_name => 'イブラヒモビッチ', :valid_st => 1 },
  { :id => 295, :type_id => 6, :full_name => 'エトー', :short_name => 'エトー', :valid_st => 1 },
  { :id => 296, :type_id => 6, :full_name => 'クライファート', :short_name => 'クライファート', :valid_st => 1 },
  { :id => 297, :type_id => 6, :full_name => 'サビオラ', :short_name => 'サビオラ', :valid_st => 1 },
  { :id => 298, :type_id => 6, :full_name => 'サリナス', :short_name => 'サリナス', :valid_st => 1 },
  { :id => 299, :type_id => 6, :full_name => 'リュドヴィク・ジュリ', :short_name => 'ジュリ', :valid_st => 1 },
  { :id => 300, :type_id => 6, :full_name => 'スアレス', :short_name => 'スアレス', :valid_st => 1 },
  { :id => 301, :type_id => 6, :full_name => 'ストイチコフ', :short_name => 'ストイチコフ', :valid_st => 1 },
  { :id => 302, :type_id => 6, :full_name => 'ネイマール', :short_name => 'ネイマール', :valid_st => 1 },
  { :id => 303, :type_id => 6, :full_name => 'ビジャ', :short_name => 'ビジャ', :valid_st => 1 },
  { :id => 304, :type_id => 6, :full_name => 'フィーゴ', :short_name => 'フィーゴ', :valid_st => 1 },
  { :id => 305, :type_id => 6, :full_name => 'ペドロ', :short_name => 'ペドロ', :valid_st => 1 },
  { :id => 306, :type_id => 6, :full_name => 'メッシ', :short_name => 'メッシ', :valid_st => 1 },
  { :id => 307, :type_id => 6, :full_name => 'ラウドルップ', :short_name => 'ラウドルップ', :valid_st => 1 },
  { :id => 308, :type_id => 6, :full_name => 'ロナウジーニョ', :short_name => 'ロナウジーニョ', :valid_st => 1 },
  { :id => 309, :type_id => 6, :full_name => 'ロナウド', :short_name => 'ロナウド', :valid_st => 1 },
  { :id => 310, :type_id => 6, :full_name => 'ロマーリオ', :short_name => 'ロマーリオ', :valid_st => 1 },
].each do |record|
  player = Player.where(:id => record[:id]).first
  if player
    player.type_id = record[:type_id]
    player.full_name = record[:full_name]
    player.short_name = record[:short_name]
    player.valid_st = record[:valid_st]
  else
    player = Player.new(record)
  end
  player.save
end

[
  { :id => 1, :type_name => '4-4-2', :title => '4-4-2(ダイヤモンド)', :css_title => '4-4-2-a', :image_position => '{"1":{"x":"122","y":"2"},"2":{"x":"256","y":"2"},"3":{"x":"189","y":"120"},"4":{"x":"62","y":"185"},"5":{"x":"189","y":"255"},"6":{"x":"316","y":"185"},"7":{"x":"40","y":"360"},"8":{"x":"137","y":"370"},"9":{"x":"240","y":"370"},"10":{"x":"337","y":"360"},"11":{"x":"189","y":"485"}}', :text_position => '' },
  { :id => 2, :type_name => '3-4-3', :title => '3-4-3(ダイヤモンド)', :css_title => '3-4-3-a', :image_position => '{"1":{"x":"189","y":"2"},"2":{"x":"63","y":"20"},"3":{"x":"314","y":"20"},"4":{"x":"43","y":"185"},"5":{"x":"189","y":"130"},"6":{"x":"336","y":"185"},"7":{"x":"189","y":"250"},"8":{"x":"63","y":"365"},"9":{"x":"189","y":"365"},"10":{"x":"314","y":"365"},"11":{"x":"189","y":"485"}}', :text_position => '' },
  { :id => 3, :type_name => '4-2-3-1', :title => '4-2-3-1', :css_title => '4-2-3-1', :image_position => '{"1":{"x":"189","y":"2"},"2":{"x":"63","y":"130"},"3":{"x":"189","y":"130"},"4":{"x":"314","y":"130"},"5":{"x":"122","y":"250"},"6":{"x":"256","y":"250"},"7":{"x":"40","y":"360"},"8":{"x":"137","y":"370"},"9":{"x":"240","y":"370"},"10":{"x":"337","y":"360"},"11":{"x":"189","y":"485"}}', :text_position => '' },
  { :id => 4, :type_name => '4-4-2', :title => '4-4-2', :css_title => '4-4-2-b', :image_position => '{"1":{"x":"122","y":"2"},"2":{"x":"256","y":"2"},"3":{"x":"122","y":"225"},"4":{"x":"40","y":"135"},"5":{"x":"256","y":"225"},"6":{"x":"337","y":"135"},"7":{"x":"40","y":"340"},"8":{"x":"137","y":"370"},"9":{"x":"240","y":"370"},"10":{"x":"337","y":"340"},"11":{"x":"189","y":"485"}}', :text_position => '' },
  { :id => 5, :type_name => '4-3-3', :title => '4-3-3', :css_title => '4-3-3', :image_position => '{"1":{"x":"189","y":"2"},"2":{"x":"48","y":"50"},"3":{"x":"189","y":"255"},"4":{"x":"329","y":"50"},"5":{"x":"122","y":"150"},"6":{"x":"256","y":"150"},"7":{"x":"40","y":"330"},"8":{"x":"137","y":"370"},"9":{"x":"240","y":"370"},"10":{"x":"337","y":"330"},"11":{"x":"189","y":"485"}}', :text_position => '' },
].each do |record|
  formation = Formation.where(:id => record[:id]).first
  if formation
    formation.type_name = record[:type_name]
    formation.title = record[:title]
    formation.css_title = record[:css_title]
    formation.image_position = record[:image_position]
    formation.text_position = record[:text_position]
  else
    formation = Formation.new(record)
  end
  formation.save
end

[
  { :id => 1, :title => '味噌汁の具', :description => '好きな具でベストイレブンを組め', :valid_player_type_ids => '[1]', :valid_st => 1 },
  { :id => 2, :title => '職業', :description => '職業毎の特徴をいかしてベストイレブンを組め', :valid_player_type_ids => '[2]', :valid_st => 1 },
  { :id => 3, :title => 'W杯戦士', :description => 'W杯戦士でベストイレブンを組め', :valid_player_type_ids => '[3]', :valid_st => 1 },
  { :id => 4, :title => '歴代レアルマドリード', :description => '歴代選手(1996〜2015年)でベストイレブンを組め', :valid_player_type_ids => '[4]', :valid_st => 1 },
  { :id => 5, :title => 'アスリート', :description => '超人的アスリートでベストイレブンを組め', :valid_player_type_ids => '[5]', :valid_st => 1 },
  { :id => 6, :title => '歴代バルセロナ', :description => '歴代選手(1988〜2015年)でベストイレブンを組め', :valid_player_type_ids => '[6]', :valid_st => 1 },
].each do |record|
  question = Question.where(:id => record[:id]).first
  if question
    question.title = record[:title]
    question.description = record[:description]
    question.valid_player_type_ids = record[:valid_player_type_ids]
    question.valid_st = record[:valid_st]
  else
    question = Question.new(record)
  end
  question.save
end

[
  { :id => 1, :title => '味噌汁の具' },
  { :id => 2, :title => '職業' },
  { :id => 3, :title => 'W杯戦士' },
  { :id => 4, :title => '歴代レアルマドリード' },
  { :id => 5, :title => 'アスリート' },
  { :id => 6, :title => '歴代バルセロナ' },
].each do |record|
  player_type = PlayerType.where(:id => record[:id]).first
  if player_type
    player_type.title = record[:title]
  else
    player_type = PlayerType.new(record)
  end
  player_type.save
end

#[
#  { :id => 1, :valid_st => 0 },
#].each do |record|
#  maintenance = Maintenance.where(:id => record[:id]).first
#  if maintenance
#    maintenance.valid_st = record[:valid_st]
#  else
#    maintenance = Maintenance.new(record)
#  end
#  maintenance.save
#end
#
